#! /bin/sh
# Derive the union register-vocabulary widths from the per-back-end probe
# objects.  See multi-target-reg-probe.cc for why this is a compile plus `nm'
# rather than a generator.
#
# Usage: gen-reg-widths.sh NM OUTPUT PROBE.o...
#
# EVERY WAY OF LEARNING NOTHING IS A FAILURE HERE.  A width that comes back
# empty, zero, or from a symbol `nm' did not print would silently size the
# HARD_REG_SET vocabulary of the whole compiler, and it would do so in the
# direction that makes the build succeed.  So: no probe objects is fatal, a
# missing symbol is fatal, a size of 0 is fatal, and a non-numeric size is
# fatal -- each naming the object and the symbol.

set -u

NM=$1; shift
OUT=$1; shift

if [ $# -eq 0 ]; then
  echo "gen-reg-widths.sh: no probe objects given; refusing to invent widths" >&2
  exit 1
fi

max_fpr=0
max_nrc=0

# One line per (object, symbol) so that a failure names both.  `nm -S' prints
# `<value> <size> <type> <name>'; the size is field 2 and is hexadecimal.
for obj in "$@"; do
  [ -s "$obj" ] || {
    echo "gen-reg-widths.sh: probe object $obj is missing or empty" >&2
    exit 1
  }
  # $NM UNQUOTED, deliberately.  Makefile.in's NM is `@NM@', which on a host
  # whose compiler wants an LTO plugin is not a program name but a COMMAND --
  # `.../bin/nm --plugin .../liblto_plugin.so -B'.  Quoted, the shell looks for
  # a single executable whose name contains spaces and reports
  # `No such file or directory', which reads as "there is no nm on this
  # machine" and is not what happened.  It has to word-split.
  syms=`$NM -S "$obj"` || {
    echo "gen-reg-widths.sh: '$NM' -S $obj failed" >&2
    exit 1
  }
  for sym in mt_probe_first_pseudo_register mt_probe_n_reg_classes; do
    # Anchor on the END of the line: `nm' prints the name last, and an
    # unanchored match would also accept a longer name that contains this one.
    line=`echo "$syms" | grep " $sym\$"` || line=
    [ -n "$line" ] || {
      echo "gen-reg-widths.sh: $obj defines no $sym." >&2
      echo "  Either the probe did not compile against this back end's tm.h," \
	   "or $NM cannot read this object.  Refusing to guess a width." >&2
      exit 1
    }
    hex=`echo "$line" | awk '{print $2}'`
    case $hex in
      [0-9a-fA-F]*) ;;
      *) echo "gen-reg-widths.sh: $obj: $sym has no size in $NM -S output ($line)" >&2
	 exit 1;;
    esac
    size=`printf '%d' "0x$hex" 2>/dev/null` || size=
    [ -n "$size" ] || {
      echo "gen-reg-widths.sh: $obj: cannot read $sym size from '$hex'" >&2
      exit 1
    }
    # The probe declares the array one byte longer than the value, so that a
    # value of 0 and a size nm failed to report are different things.
    val=`expr "$size" - 1`
    if [ "$size" -le 0 ] || [ "$val" -le 0 ]; then
      echo "gen-reg-widths.sh: $obj: $sym measured $val, which no back end has." >&2
      exit 1
    fi
    case $sym in
      mt_probe_first_pseudo_register)
	[ "$val" -gt "$max_fpr" ] && max_fpr=$val;;
      mt_probe_n_reg_classes)
	[ "$val" -gt "$max_nrc" ] && max_nrc=$val;;
    esac
  done
done

if [ "$max_fpr" -le 0 ] || [ "$max_nrc" -le 0 ]; then
  echo "gen-reg-widths.sh: ended with fpr=$max_fpr nrc=$max_nrc; refusing" >&2
  exit 1
fi

cat > "$OUT".tmp <<EOF
/* Generated by gen-reg-widths.sh from the per-back-end probe objects.
   Do not edit.  See multi-target-reg-probe.cc.

   These are COMPILE-TIME MAXIMA over the configured back ends, and they are
   the same in every translation unit of the compiler -- back ends' own
   objects included.  That is not an optimisation: \`struct target_hard_regs',
   \`struct target_regs', \`struct target_ira' and \`struct target_ira_int' are
   sized by these names and are allocated by generic code
   (target-globals.cc:71-89, XCNEW) while every back end's own translation
   unit reads the same fields.  One authority for the size, several for the
   contents, is the \`cl_optimization' shape this branch exists to remove.

   A base's OWN widths are not lost: defaults.h captures them as
   \`multi_target_own_*' before overriding, and target-regs.cc reports them at
   run time.  The loops belong to the selected base's counts; the LAYOUT
   belongs to these.  */

#ifndef GCC_MULTI_TARGET_REG_WIDTHS_H
#define GCC_MULTI_TARGET_REG_WIDTHS_H

#define MULTI_TARGET_UNION_FIRST_PSEUDO_REGISTER $max_fpr
#define MULTI_TARGET_UNION_N_REG_CLASSES $max_nrc

#endif /* GCC_MULTI_TARGET_REG_WIDTHS_H */
EOF

# move-if-change, not `mv'.  Every other generated header on this branch uses
# it, and here it matters more than tidiness: this header is a prerequisite of
# every back end's objects, so rewriting it unconditionally would make a
# no-op `make' rebuild the compiler.
if [ -f "$OUT" ] && cmp -s "$OUT".tmp "$OUT"; then
  rm -f "$OUT".tmp
else
  mv -f "$OUT".tmp "$OUT"
fi
