#! /bin/sh

# Copyright (C) 2026 Free Software Foundation, Inc.
# This file is part of GCC.
#
# GCC is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3, or (at your option) any later version.
#
# GCC is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with GCC; see the file COPYING3.  If not see
# <http://www.gnu.org/licenses/>.

# Build the multi-target manifest and everything derived from it, one stanza
# per configured target.
#
# Why this is a script and not more shell in gcc/configure.ac: configure.ac is
# about the host and the build machine.  A loop that sources config.gcc once
# per target and writes per-target make rules is target configuration, and it
# had grown to a third of the file.  Nothing here probes the host, so nothing
# here needs autoconf; it needs a shell, config.sub, config.gcc and awk.
#
# Usage:
#
#   . ${srcdir}/gen-target-manifest.sh
#   gcc_gen_target_manifest || AC_MSG_ERROR([... ${gcc_mt_fatal}])
#
# This one is SOURCED, where gen-multilib-data.sh is run.  It has to be:
# config.gcc reads some seventy of configure's own `enable_*' and `with_*'
# variables -- `enable_multilib', `enable_threads', `with_arch', ... -- and
# configure does not export them.  A child process would source config.gcc
# with those unset and get a different, silently plausible answer for every
# target that consults one.  Sourcing keeps the loop in configure's shell,
# which is exactly where the single-target `. ${srcdir}/config.gcc' above it
# already runs.
#
# Inputs, all already set by configure at the point of the call:
#
#   srcdir                  gcc source directory
#   AWK                     awk to use
#   gcc_manifest_targets    the raw target list, primary target included.  It
#                           is canonicalised and deduplicated here, so the
#                           caller does not have to.
#
# Writes, in the current directory:
#
#   multi-target.manifest           one blank-line-separated stanza per target
#   multi-target-common.mk          per-target make rules
#   multi-target-common.h           the common-hook table registry
#   multi-target-spec-functions.h   the driver spec-function table registry
#
# and leaves set, in the caller's shell: gcc_manifest_targets (now
# canonicalised), gcc_all_common_objects, gcc_all_common_symbols,
# gcc_all_spec_fn_objects, gcc_all_target_gtfiles.
#
# On failure it sets gcc_mt_fatal to the reason and returns 1.  It does not
# exit and does not print: the caller owns the diagnostic, so that a half
# written manifest cannot be mistaken for a source bug.

gcc_gen_target_manifest () {

gcc_mt_fatal=

if test x"${gcc_manifest_targets}" = x; then
  gcc_mt_fatal="no targets given"
  return 1
fi

gcc_all_common_objects=
gcc_all_common_symbols=
gcc_all_target_gtfiles=
gcc_common_mk=multi-target-common.mk
echo "# Generated by configure: one rule per target's common hook table." > ${gcc_common_mk}
# Registry of the tables, as data for common/common-target-select.cc.
# Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1752".
gcc_common_ext=multi-target-common.ext
gcc_common_ent=multi-target-common.ent
: > ${gcc_common_ext}
: > ${gcc_common_ent}
# The same two pieces for the driver's spec-function tables.
# Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1759".
gcc_all_spec_fn_objects=
gcc_sf_ext=multi-target-spec-functions.ext
gcc_sf_ent=multi-target-spec-functions.ent
: > ${gcc_sf_ext}
: > ${gcc_sf_ent}
gcc_target_manifest=multi-target.manifest
: > ${gcc_target_manifest}
gcc_mt_err=conftest.mterr

#
# Canonicalise the list, and deduplicate it once canonical.
# Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1772".
gcc_mt_canon=
for gcc_mt in ${gcc_manifest_targets}; do
  gcc_mt_c=`${srcdir}/../config.sub ${gcc_mt} 2> ${gcc_mt_err}`
  if test x"${gcc_mt_c}" = x; then
    gcc_mt_fatal="${gcc_mt} is not a recognised target name"
    return 1
  fi
  gcc_mt_seen=no
  for gcc_mt_have in ${gcc_mt_canon}; do
    if test x"${gcc_mt_have}" = x"${gcc_mt_c}"; then
      gcc_mt_seen=yes
    fi
  done
  if test x"${gcc_mt_seen}" = xno; then
    gcc_mt_canon="${gcc_mt_canon} ${gcc_mt_c}"
  fi
done
gcc_manifest_targets=${gcc_mt_canon}

for gcc_mt in ${gcc_manifest_targets}; do
  # The with_* group no longer needs clearing here:
  # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1804".
  gcc_mt_data=`
    target=${gcc_mt}
    tm_defines= cpu_type= target_cpu_default=
    tm_file= tm_p_file= tmake_file=
    extra_objs= extra_options= extra_headers=
    out_file= md_file= target_gtfiles=
    common_out_file= target_has_targetm_common= dwarf2= extra_modes=
    TM_MULTILIB_CONFIG=
    . ${srcdir}/config.gcc 2> ${gcc_mt_err} > /dev/null || exit 1
    # config.gcc leaves these unset for most targets; the primary target gets
    # them defaulted just below, ...
    # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1818".
    test x"${tm_file}" = x && tm_file=${cpu_type}/${cpu_type}.h
    test x"${md_file}" = x && md_file=${cpu_type}/${cpu_type}.md
    test x"${out_file}" = x && out_file=${cpu_type}/${cpu_type}.cc
    echo "target ${gcc_mt}"
    echo "cpu_type ${cpu_type}"
    # This targets own CPU/ABI defaults, as name=value pairs whose names are
    # the OPTION_DEFAULT_SPECS ...
    # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1826".
    echo "option_defaults ${target_option_defaults}"
    # Target properties cc1 needs that are decided by the triple, not probed.
    echo "decimal_float ${target_decimal_float}"
    echo "decimal_bid_format ${target_decimal_bid_format}"
    # Which common-hook table this target uses, and the name it will be
    # compiled under.
    # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1837".
    echo "common_out_file ${common_out_file}"
    # Use $( ) here, not backticks.
    # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1842".
    echo "common_out_symbol targetm_common_$(basename ${common_out_file} .cc | sed 's/-/_/g')"
    echo "tm_file ${tm_file}"
    echo "tm_p_file ${tm_p_file}"
    echo "tmake_file ${tmake_file}"
    # Which of those fragments actually exist.
    # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1850".
    mt_tmake_present=
    for mt_tf in ${tmake_file}; do
      if test -f ${srcdir}/config/${mt_tf}; then
	mt_tmake_present="${mt_tmake_present} ${mt_tf}"
      fi
    done
    echo "tmake_file_present ${mt_tmake_present}"
    echo "extra_objs ${extra_objs}"
    echo "extra_options ${extra_options}"
    echo "out_file ${out_file}"
    echo "md_file ${md_file}"
    # The back-end sources gengtype must scan for GTY markers.  gengtype makes
    # ONE pass over a global GTFILES and names its output after the source
    # file (gt-arm.h from config/arm/arm.cc), so unlike the insn-* generators
    # this needs a union, not a rule per back end -- the names cannot collide.
    # Recorded here because configure's own ${target_gtfiles} is the PRIMARY
    # target's alone, which is why gt-<cpu>.h had no rule for anyone else.
    echo "target_gtfiles ${target_gtfiles}"
    # The header list this target's tm.h is built from, in the same form the
    # single-target path uses.
    # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1871".
    mt_tm_file="${tm_file} initfini-array.h"
    if test x"${dwarf2}" = xyes; then
      mt_tm_file="${mt_tm_file} tm-dwarf2.h"
    fi
    mt_tm_file="${mt_tm_file} defaults.h"

    mt_tm_include_list="options.h insn-constants.h"
    for mt_f in ${mt_tm_file}; do
      case ${mt_f} in
	./* ) mt_tm_include_list="${mt_tm_include_list} $(echo ${mt_f} | sed 's/^..//')" ;;
	defaults.h ) mt_tm_include_list="${mt_tm_include_list} ${mt_f}" ;;
	* ) mt_tm_include_list="${mt_tm_include_list} config/${mt_f}" ;;
      esac
    done
    echo "tm_include_list ${mt_tm_include_list}"
    echo "tm_defines ${tm_defines}"
    # The value TARGET_CPU_DEFAULT must have in this target's tm.h.  Without it
    # a back end that reads the macro -- nds32 does -- does not compile.
    echo "target_cpu_default ${target_cpu_default}"
    # This back end's extra machine modes.
    # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1899".
    echo "extra_modes ${extra_modes}"
    # Headers this target's tm.h includes that no source tree contains:
    # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1906".
    mt_tm_gen_headers=
    for mt_f in ${tm_file}; do
      case ${mt_f} in
	./* ) mt_tm_gen_headers="${mt_tm_gen_headers} $(echo ${mt_f} | sed 's/^..//')" ;;
      esac
    done
    echo "tm_generated_headers ${mt_tm_gen_headers}"
    #
    # The multilib set is NOT a config.gcc variable:
    # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1918".
    echo "tm_multilib_config ${TM_MULTILIB_CONFIG}"
  ` || {
    # Read the message here, not in the diagnostic's argument:
    # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1932".
    gcc_mt_msg=`tr '\n' ' ' < ${gcc_mt_err}`
    gcc_mt_fatal="config.gcc failed for ${gcc_mt}: ${gcc_mt_msg}"
    return 1
  }
  echo "${gcc_mt_data}" >> ${gcc_target_manifest}
  echo "" >> ${gcc_target_manifest}

  # Collect each target's common-hook table so the build can compile all of
  # them.
  # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1941".
  gcc_mt_cof=`echo "${gcc_mt_data}" | sed -n 's/^common_out_file //p'`
  gcc_mt_sym=`echo "${gcc_mt_data}" | sed -n 's/^common_out_symbol //p'`
  gcc_mt_obj=`basename ${gcc_mt_cof} .cc`.o
  gcc_mt_base=`basename ${gcc_mt_cof} -common.cc`
  gcc_mt_incl=`echo "${gcc_mt_data}" | sed -n 's/^tm_include_list //p'`
  # cpu_type, not the -common.cc base: the t-<cpu>-headers fragments are named
  # after cpu_type, which is the key gen-multi-target-md.awk includes them by.
  gcc_mt_cpu=`echo "${gcc_mt_data}" | sed -n 's/^cpu_type //p'`
  gcc_mt_tmdef=`echo "${gcc_mt_data}" | sed -n 's/^tm_defines //p'`
  gcc_mt_eopts=`echo "${gcc_mt_data}" | sed -n 's/^extra_options //p'`
  # This target's tm.h must pull in this target's options.h, not the generic
  # one:
  # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1952".
  gcc_mt_md=`echo "${gcc_mt_data}" | sed -n 's/^md_file //p'`
  gcc_mt_incl=`echo "${gcc_mt_incl}" | sed -e "s|^options\.h|options-${gcc_mt_base}.h|" -e "s|insn-constants\.h|insn-constants-${gcc_mt_base}.h|"`
  # config.gcc sets this per target and some back ends' tm.h reads it (nds32
  # builds its default ISA out ...
  # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1959".
  gcc_mt_tcd=`echo "${gcc_mt_data}" | sed -n 's/^target_cpu_default //p'`
  # Union the gengtype inputs across every configured target.  Deduplicated
  # because two triples of one back end name the same files, and gengtype
  # given a file twice emits its gt- header twice.
  gcc_mt_gtf=`echo "${gcc_mt_data}" | sed -n 's/^target_gtfiles //p'`
  # A back end's MAIN source is not in target_gtfiles: config.gcc lists only
  # the extra files, and gcc/Makefile.in picks up the main one as the singular
  # $(out_file) -- the primary target's, which is why gt-i386.h was the only
  # back-end gt- header a multi-target build produced.  Union it here too.
  gcc_mt_gtf="${gcc_mt_gtf} \$(srcdir)/config/`echo "${gcc_mt_data}" | sed -n 's/^out_file //p'`"
  for gcc_mt_f in ${gcc_mt_gtf}; do
    case " ${gcc_all_target_gtfiles} " in
      *" ${gcc_mt_f} "*) ;;
      *) gcc_all_target_gtfiles="${gcc_all_target_gtfiles} ${gcc_mt_f}" ;;
    esac
  done
  # The same treatment for the headers a target's tmake_file would generate
  # into the build directory.
  # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1963".
  gcc_mt_genh=`echo "${gcc_mt_data}" | sed -n 's/^tm_generated_headers //p'`
  gcc_mt_genh_files=
  for gcc_mt_h in ${gcc_mt_genh}; do
    gcc_mt_hb=`basename ${gcc_mt_h} .h`
    gcc_mt_incl=`echo "${gcc_mt_incl}" | sed -e "s|\\([ ]\\)${gcc_mt_hb}\\.h|\\1${gcc_mt_hb}-${gcc_mt_base}.h|g"`
    gcc_mt_genh_files="${gcc_mt_genh_files} ${gcc_mt_hb}-${gcc_mt_base}.h"
  done
  # gcc_mt_eopts is deliberately NOT turned into a make rule here.  It is read
  # back out of the manifest by the union pass after this loop; see there.
  case " ${gcc_all_common_objects} " in
    *" ${gcc_mt_obj} "*) ;;
    *) gcc_all_common_objects="${gcc_all_common_objects} ${gcc_mt_obj}"
       gcc_all_common_symbols="${gcc_all_common_symbols} ${gcc_mt_sym}"
       # One rule per object. A pattern rule cannot serve here:
       # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1980".
       if test x"${gcc_mt_base}" != xdefault; then
         # This back end's own options header is NOT emitted here.
         # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1989".
         printf 'insn-constants-%s.h: build/genconstants$(build_exeext) $(srcdir)/config/%s\n\t$(RUN_GEN) build/genconstants$(build_exeext) $(srcdir)/config/%s > $@\n\n' \
           "${gcc_mt_base}" "${gcc_mt_md}" "${gcc_mt_md}" >> ${gcc_common_mk}
         #
         # The build-directory headers this target's tm.h includes, holding
         # multilib-derived spec macros -- ...
         # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:1997".
         for gcc_mt_h in ${gcc_mt_genh_files}; do
           case ${gcc_mt_h} in
             *sysroot-suffix*)
               printf '%s: multi-target.manifest multi-target.multilib $(srcdir)/gen-sysroot-suffix.sh\n\t$(SHELL) $(srcdir)/gen-sysroot-suffix.sh %s multi-target.manifest multi-target.multilib $(srcdir) > $@\n\n' \
                 "${gcc_mt_h}" "${gcc_mt}" >> ${gcc_common_mk}
               ;;
             *)
               # The rest are headers a config/<cpu>/t-<cpu>-headers fragment already
               # generates under its plain ...
               # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:2015".
               #
               # *** The `cp' below is only correct while the PLAIN name has a
               # real rule, and the only thing that gives it one in a
               # multi-target build is config/<cpu>/t-<cpu>-headers, which
               # gen-multi-target-md.awk includes unconditionally.  Without the
               # fragment the plain name is whatever the last single-target
               # build left in the directory, and `cp' propagates that stale
               # file into tm-<base>.h without a word.  That is exactly how
               # every arm spec file came to be generated against a stale
               # arm-cpu.h: the rules lived in t-arm, which is included only
               # when arm is PRIMARY, so no other build ever regenerated it.
               #
               # So refuse, loudly, rather than emit a rule that reads a file
               # nothing writes.  A back end reaching here without a fragment
               # is not misconfigured by the user; it means whoever added it
               # has a t-<cpu>-headers split left to do.
               gcc_mt_horig=`echo "${gcc_mt_h}" | sed "s/-${gcc_mt_base}\\.h\$/.h/"`
               if test -f ${srcdir}/config/${gcc_mt_cpu}/t-${gcc_mt_cpu}-headers; then :; else
                 gcc_mt_fatal="${gcc_mt} needs ${gcc_mt_h}, which is copied from\
 the generated ${gcc_mt_horig}, but config/${gcc_mt_cpu}/t-${gcc_mt_cpu}-headers\
 does not exist.  Only that fragment gives ${gcc_mt_horig} a rule in a\
 multi-target build; without it the copy would silently propagate whatever\
 stale ${gcc_mt_horig} happens to be in the build directory.  Split the rules\
 that generate ${gcc_mt_horig} out of config/${gcc_mt_cpu}/t-${gcc_mt_cpu} into\
 config/${gcc_mt_cpu}/t-${gcc_mt_cpu}-headers, the way\
 config/arm/t-arm-headers and config/loongarch/t-loongarch-headers already do."
                 return 1
               fi
               printf '%s: %s\n\tcp $< $@\n\n' \
                 "${gcc_mt_h}" "${gcc_mt_horig}" >> ${gcc_common_mk}
               ;;
           esac
         done
         # INSN_BASE: mkconfig.sh needs the back end told to it rather than
         # read off the output name.  Here the two coincide, but stating it
         # keeps this call site and the per-triple one in
         # gen-multi-target-md.awk the same shape, and mkconfig.sh now refuses
         # a tm-*.h without it.
         printf 'tm-%s.h: options-%s.h insn-constants-%s.h%s Makefile\n\tTARGET_CPU_DEFAULT="%s" HEADERS="%s" DEFINES="%s" \\\n\t  INSN_BASE="%s" $(SHELL) $(srcdir)/mkconfig.sh tm-%s.h\n\n' \
           "${gcc_mt_base}" "${gcc_mt_base}" "${gcc_mt_base}" "${gcc_mt_genh_files}" "${gcc_mt_tcd}" "${gcc_mt_incl}" "${gcc_mt_tmdef}" "${gcc_mt_base}" "${gcc_mt_base}" >> ${gcc_common_mk}
         printf '%s: $(srcdir)/common/config/%s tm-%s.h\n\t$(COMPILE) -DTARGETM_COMMON_SYMBOL=%s $<\n\t$(POSTCOMPILE)\n\n' \
           "${gcc_mt_obj}" "${gcc_mt_cof}" "${gcc_mt_base}" "${gcc_mt_sym}" >> ${gcc_common_mk}
         # This back end's driver spec functions, from the same tm-<base>.h.
         # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:2034".
         gcc_mt_tmflag="-DTM_H_FILE='\"tm-${gcc_mt_base}.h\"'"
         printf 'spec-functions-%s.o: $(srcdir)/spec-functions.cc tm-%s.h $(GCC_H)\n\t$(COMPILE) %s -DSPEC_FUNCTIONS_SYMBOL=extra_spec_functions_%s $(srcdir)/spec-functions.cc\n\t$(POSTCOMPILE)\n\n' \
           "${gcc_mt_base}" "${gcc_mt_base}" "${gcc_mt_tmflag}" "${gcc_mt_base}" >> ${gcc_common_mk}
         gcc_all_spec_fn_objects="${gcc_all_spec_fn_objects} spec-functions-${gcc_mt_base}.o"
         printf 'extern const struct spec_function extra_spec_functions_%s[];\n' \
           "${gcc_mt_base}" >> ${gcc_sf_ext}
       else
         printf '%s: $(srcdir)/common/config/%s\n\t$(COMPILE) -DTARGETM_COMMON_SYMBOL=%s $<\n\t$(POSTCOMPILE)\n\n' \
           "${gcc_mt_obj}" "${gcc_mt_cof}" "${gcc_mt_sym}" >> ${gcc_common_mk}
       fi
       printf 'extern struct gcc_targetm_common %s;\n' "${gcc_mt_sym}" >> ${gcc_common_ext}
       ;;
  esac
  # One entry per target, not per object:
  # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:2062".
  printf '  TARGETM_COMMON_ENTRY ("%s", %s) \\\n' "${gcc_mt}" "${gcc_mt_sym}" >> ${gcc_common_ent}
  # And one spec-function entry per target, for the same reason.
  # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:2067".
  if test x"${gcc_mt_base}" != xdefault; then
    printf '  SPEC_FUNCTIONS_ENTRY ("%s", extra_spec_functions_%s) \\\n' \
      "${gcc_mt}" "${gcc_mt_base}" >> ${gcc_sf_ent}
  else
    printf '  SPEC_FUNCTIONS_ENTRY ("%s", spec_functions_empty) \\\n' \
      "${gcc_mt}" >> ${gcc_sf_ent}
  fi
done
rm -f ${gcc_mt_err}

#
#
#
# The options header of a back end, built from the UNION of its triples'
# extra_options.
# Why: gcc/CONFIGURE-HISTORY.md "configure.ac:2082".
${AWK} '
  # Manifest stanzas are blank-line separated `key value...` lines.
  /^common_out_file / {
    base = $2
    sub(/.*\//, "", base)
    sub(/-common\.cc$/, "", base)
    next
  }
  /^extra_options / {
    for (i = 2; i <= NF; i++)
      opt[i] = $i
    n = NF
    next
  }
  /^$/ { flush() }
  END { flush() }

  function flush(   i, f) {
    # default-common.cc back ends have no options-<base>.h at all.
    if (base != "" && base != "default") {
      for (i = 2; i <= n; i++) {
	f = opt[i]
	# Order is preserved and duplicates dropped: opt-gather.awk is fed
	# each file once, and a file listed twice would be gathered twice.
	if (!((base SUBSEP f) in seen)) {
	  seen[base SUBSEP f] = 1
	  files[base] = files[base] " $(srcdir)/config/" f
	}
	# ... and the same files unioned across ALL back ends.
	# Why: gcc/CONFIGURE-HISTORY.md "configure.ac:2138".
	if (!(f in seenall)) {
	  seenall[f] = 1
	  allfiles = allfiles " $(srcdir)/config/" f
	}
      }
      if (!(base in emitted)) {
	emitted[base] = 1
	order[++nbase] = base
      }
    }
    base = ""; n = 0
  }

  END {
    # The .opt files of every configured back end.  gcc/Makefile.in feeds this to
    # opt-gather.awk to build optionlist-vocab, the union of option NAMES.
    printf "MT_OPT_UNION_FILES =%s\n\n", allfiles
    for (i = 1; i <= nbase; i++) {
      b = order[i]
      # This back end own records, PLUS a placeholder for every name in the
      # vocabulary it does not declare.
      # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:2162".
      printf "optionlist-%s: $(lang_opt_files)%s optionlist-vocab $(srcdir)/opt-gather.awk $(srcdir)/opt-functions.awk $(srcdir)/opt-stub.awk\n", b, files[b]
      printf "\tLC_ALL=C; export LC_ALL; \\\n"
      printf "\t$(AWK) -f $(srcdir)/opt-gather.awk $(lang_opt_files)%s > $@.own\n", files[b]
      printf "\t$(AWK) -f $(srcdir)/opt-functions.awk -f $(srcdir)/opt-stub.awk \\\n"
      printf "\t  -v vocab=optionlist-vocab optionlist-vocab $@.own > $@.stub\n"
      printf "\t@echo \"$@: `wc -l < $@.own` own + `wc -l < $@.stub` placeholder records\"\n"
      printf "\tLC_ALL=C; export LC_ALL; \\\n"
      printf "\tcat $@.own $@.stub | sort > $@\n"
      printf "\trm -f $@.own $@.stub\n\n"
      printf "options-%s.h: optionlist-%s $(srcdir)/opt-functions.awk $(srcdir)/opt-read.awk $(srcdir)/opth-gen.awk\n", b, b
      printf "\t$(AWK) -f $(srcdir)/opt-functions.awk -f $(srcdir)/opt-read.awk \\\n"
      # A guard of its own. Sharing one guard across the shared options.h and
      # the other 44 made a second ...
      # Why: gcc/CONFIGURE-HISTORY.md "configure.ac:2181".
      printf "\t  -v guard_name=OPTIONS_%s_H \\\n", toupper(b)
      printf "\t  -f $(srcdir)/opth-gen.awk < $< > $@\n\n"
    }
  }
' ${gcc_target_manifest} >> ${gcc_common_mk}

# Assemble the registry header from the two pieces.
{
  echo "/* Generated by configure.  Every configured target's common hook table."
  echo "   Do not edit.  */"
  echo ""
  cat ${gcc_common_ext}
  echo ""
  echo "#define TARGETM_COMMON_TABLES \\"
  cat ${gcc_common_ent}
  echo "  /* end of table */"
} > multi-target-common.h
rm -f ${gcc_common_ext} ${gcc_common_ent}

# The same, for the driver's spec-function tables.
{
  echo "/* Generated by configure.  Every configured target's driver"
  echo "   spec-function table.  Do not edit.  */"
  echo ""
  cat ${gcc_sf_ext}
  echo ""
  echo "#define SPEC_FUNCTIONS_TABLES \\"
  cat ${gcc_sf_ent}
  echo "  /* end of table */"
} > multi-target-spec-functions.h
rm -f ${gcc_sf_ext} ${gcc_sf_ent}

# gcc_manifest_targets, gcc_all_common_objects, gcc_all_common_symbols,
# gcc_all_spec_fn_objects and gcc_all_target_gtfiles are left set for the
# caller to AC_SUBST.
return 0

}
