#  Copyright (C) 2013-2026 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING3.  If not see
# <http://www.gnu.org/licenses/>.

# This Awk script takes passes.def and writes pass-instances.def,
# counting the instances of each kind of pass, adding an instance number
# to everywhere that NEXT_PASS or PUSH_INSERT_PASSES_WITHIN are used.
# Also handle INSERT_PASS_AFTER, INSERT_PASS_BEFORE and REPLACE_PASS
# directives.
#
# For example, the single-instanced pass:
#     NEXT_PASS (pass_warn_unused_result);
# becomes this in the output:
#     NEXT_PASS (pass_warn_unused_result, 1);
#
# The various instances of
#   NEXT_PASS (pass_copy_prop);
# become:
#   NEXT_PASS (pass_copy_prop, 1);
# through:
#   NEXT_PASS (pass_copy_prop, 8);
# (currently there are 8 instances of that pass)
#
#     INSERT_PASS_AFTER (pass_copy_prop, 1, pass_stv);
# will insert
#     NEXT_PASS (pass_stv, 1);
# immediately after the NEXT_PASS (pass_copy_prop, 1) line,
# similarly INSERT_PASS_BEFORE inserts immediately before that line.
#     REPLACE_PASS (pass_copy_prop, 1, pass_stv, true);
# will replace NEXT_PASS (pass_copy_prop, 1) line with
#     NEXT_PASS (pass_stv, 1, true);
# line and renumber all higher pass_copy_prop instances if any.

# Usage: awk -f gen-pass-instances.awk passes.def
#        awk -f gen-pass-instances.awk -v pass_bases="<file>=<base> ..." \
#            passes.def <file> ...
#
# MULTI-TARGET: EVERY EXTRA FILE MUST NAME THE BACK END IT BELONGS TO.
#
# Upstream, `pass-instances.def' describes ONE target, so a target pass needs
# no owner: whatever `<cpu>-passes.def' the single tmake_file dragged in is by
# definition the compiler's own.  Here the file describes every configured
# back end at once, and two things follow that upstream never has to face:
#
#   * two back ends can contribute a pass of the SAME NAME.  aarch64 and arm
#     both say `INSERT_PASS_BEFORE (pass_shorten_branches, 1, pass_insert_bti)'
#     and they are two different passes.  Untagged they become instances 1 and
#     2 of one name, and passes.cc builds instance 2 as `m_..._1->clone ()' --
#     arm's BTI pass silently becomes a copy of aarch64's.  This is not a link
#     error; it is the project's `shared numbering' bug in the pass manager.
#   * the factory `make_pass_insert_bti' is defined bare by both back ends and
#     is therefore in MULTI_TARGET_RENAME_NAMES, so no single bare name exists
#     for shared code to call.
#
# Both are answered by the same tag: a directive read from a file tagged
# `=<base>' has its INSERTED pass renamed `<pass>_mt_<base>'.  The anchor pass
# -- the first argument, a shared pass -- is NOT renamed.  Shared passes.cc
# then calls `make_<pass>_mt_<base>', a forwarder generated per back end by
# gen-target-passes.awk from the same `<cpu>-passes.def', compiled with that
# back end's headers and that back end's renames.  So shared code never spells
# a renamed name and the rename list needs no change.
#
# An extra file with no tag is REFUSED BY NAME rather than passed through
# untagged.  The untagged path is exactly the defect being fixed: PASSES_EXTRA
# used to be fed only by `-include $(tmake_file)', which a multi-target build
# substitutes with the legacy single `${target}'s fragments alone, so
# pass-instances.def carried i386's three target passes and not one from any
# other configured back end.  Making the untagged case an error means that
# channel cannot quietly come back.

function fatal(msg) {
  print "gen-pass-instances.awk: " msg > "/dev/stderr";
  bad = 1;
  exit 1;
}

BEGIN {
  print "/* This file is auto-generated by gen-pass-instances.awk";
  print "   from passes.def.  */";
  lineno = 1;
  bad = 0;
  nb = split(pass_bases, bpairs, " ");
  for (bi = 1; bi <= nb; bi++)
    {
      beq = index(bpairs[bi], "=");
      if (beq == 0)
	fatal("pass_bases entry `" bpairs[bi] "' is not <file>=<base>");
      base_of[substr(bpairs[bi], 1, beq - 1)] = substr(bpairs[bi], beq + 1);
    }
}

# The owning back end of the file now being read.  ARGV[1] is passes.def, the
# target-independent list, and it is the only file allowed to be untagged.
FNR == 1 {
  if (FILENAME == ARGV[1])
    cur_base = "";
  else if (FILENAME in base_of)
    cur_base = base_of[FILENAME];
  else
    fatal("`" FILENAME "' is in PASSES_EXTRA but no back end claims it." \
	  "  A target pass file must arrive through the back-end list with" \
	  " a `<file>=<base>' tag, not through $(tmake_file), which names" \
	  " one target's fragments alone.");
}

function parse_line(line, fnname,	len_of_call, len_of_start,
					len_of_open, len_of_close,
					len_of_args, args_start_at,
					args_str, len_of_prefix,
					call_starts_at,
					postfix_starts_at)
{
  # Find call expression.
  call_starts_at = match(line, fnname " \\(.+\\)");
  if (call_starts_at == 0)
    return 0;

  # Length of the call expression.
  len_of_call = RLENGTH;

  len_of_start = length(fnname " (");
  len_of_open = length("(");
  len_of_close = length(")");

  # Find arguments
  len_of_args = len_of_call - (len_of_start + len_of_close);
  args_start_at = call_starts_at + len_of_start;
  args_str = substr(line, args_start_at, len_of_args);
  split(args_str, args, ",");

  # Find call expression prefix
  len_of_prefix = call_starts_at - 1;
  prefix = substr(line, 1, len_of_prefix);

  # Find call expression postfix
  postfix_starts_at = call_starts_at + len_of_call;
  postfix = substr(line, postfix_starts_at);
  return 1;
}

function adjust_linenos(above, increment,	p, i)
{
  for (p in pass_lines)
    if (pass_lines[p] >= above)
      pass_lines[p] += increment;
  if (increment > 0)
    for (i = lineno - 1; i >= above; i--)
      lines[i + increment] = lines[i];
  else
    for (i = above; i < lineno; i++)
      lines[i + increment] = lines[i];
  lineno += increment;
}

function insert_remove_pass(line, fnname,	arg3, i)
{
  parse_line($0, fnname);
  pass_name = args[1];
  if (pass_name == "PASS")
    return 1;
  pass_num = args[2] + 0;
  arg3 = args[3];
  sub(/^[ \t]*/, "", arg3);
  # The INSERTED pass belongs to the back end whose file this directive came
  # from; the anchor (args[1]) is a shared pass and keeps its name.
  if (cur_base != "")
    {
      arg3 = arg3 "_mt_" cur_base;
      args[3] = arg3;
    }
  new_line = prefix "NEXT_PASS (" arg3;
  # Add the optional params back.
  i = 4;
  while (args[i])
    {
      new_line = new_line "," args[i];
      i++;
    }
  new_line = new_line ")" postfix;
  if (!pass_lines[pass_name, pass_num])
    {
      # Was a `print' to STDOUT, i.e. into pass-instances.def itself, where it
      # becomes a C syntax error some distance from anything that names this
      # generator -- and where a `make -k' run scrolls it past.  With eight
      # back ends' files feeding this script, an anchor a back end names and
      # passes.def does not have is a thing that can actually happen, so it
      # fails here, by name, with a non-zero status.
      fatal(fnname " names pass `" pass_name "' instance " pass_num \
	    ", which passes.def does not have" \
	    (cur_base == "" ? "" : " (from back end `" cur_base "')"));
    }
  return 0;
}

function insert_pass(line, fnname, after,		num)
{
  if (insert_remove_pass(line, fnname))
    return;
  num = pass_lines[pass_name, pass_num];
  adjust_linenos(num + after, 1);
  pass_name = args[3];
  # Set pass_counts
  if (args[3] in pass_counts)
    pass_counts[pass_name]++;
  else
    pass_counts[pass_name] = 1;

  pass_lines[pass_name, pass_counts[pass_name]] = num + after;
  lines[num + after] = new_line;
}

function replace_pass(line, fnname,			num, i)
{
  if (insert_remove_pass(line, "REPLACE_PASS"))
    return;
  num = pass_lines[pass_name, pass_num];
  for (i = pass_counts[pass_name]; i > pass_num; i--)
    pass_lines[pass_name, i - 1] = pass_lines[pass_name, i];
  delete pass_lines[pass_name, pass_counts[pass_name]];
  if (pass_counts[pass_name] == 1)
    delete pass_counts[pass_name];
  else
    pass_counts[pass_name]--;

  pass_name = args[3];
  # Set pass_counts
  if (args[3] in pass_counts)
    pass_counts[pass_name]++;
  else
    pass_counts[pass_name] = 1;

  pass_lines[pass_name, pass_counts[pass_name]] = num;
  lines[num] = new_line;
}

/^[ \t]*INSERT_PASS_AFTER \(.+\)/ {
  insert_pass($0, "INSERT_PASS_AFTER", 1);
  next;
}

/^[ \t]*INSERT_PASS_BEFORE \(.+\)/ {
  insert_pass($0, "INSERT_PASS_BEFORE", 0);
  next;
}

/^[ \t]*REPLACE_PASS \(.+\)/ {
  # A back end may not REPLACE a shared pass, and this is a design refusal
  # rather than an implementation gap.  There is ONE pass-instances.def and
  # ONE compiled-once NEXT_PASS walk serving every configured back end, so a
  # replacement is not per-base: it would delete the shared pass for the seven
  # back ends that did not ask for it.  Insertions are safe because an
  # inserted pass carries its owner and is gated off for everyone else; a
  # deletion cannot be gated, because the thing it removes is not there to
  # test.  No in-tree back end uses REPLACE_PASS today -- the only occurrences
  # are in the four `Macros that can be used in this file' comments -- so this
  # refuses something nobody does, on purpose, before someone does it.
  #
  # `REPLACE_PASS (PASS, INSTANCE, TGT_PASS)' with those literal words is the
  # `Macros that can be used in this file' comment that four back ends carry,
  # not a directive -- insert_remove_pass() below drops it by the same test.
  # A refusal that fires on documentation would have blocked i386, rs6000,
  # sparc and visium, which is how an over-eager check gets relaxed to
  # nothing.
  if (cur_base != "" && $0 !~ /REPLACE_PASS[ \t]*\([ \t]*PASS[ \t]*,/)
    fatal("REPLACE_PASS in " FILENAME " (back end `" cur_base "'):" \
	  " a back end cannot replace a pass in the shared pass list --" \
	  " one list serves every configured back end and the replacement" \
	  " would apply to all of them.  Use INSERT_PASS_BEFORE/AFTER.");
  replace_pass($0, "REPLACE_PASS");
  next;
}

{
  ret = parse_line($0, "NEXT_PASS");
  if (ret)
    {
      pass_name = args[1];

      # Set pass_counts
      if (pass_name in pass_counts)
	pass_counts[pass_name]++;
      else
	pass_counts[pass_name] = 1;

      pass_lines[pass_name, pass_counts[pass_name]] = lineno;
    }
  lines[lineno++] = $0;
}

END {
  # `exit' inside a rule runs END, so without this a refusal would still emit
  # a whole plausible pass-instances.def on stdout -- and the caller writes it
  # to a temporary and then move-if-change, which would keep it.  A diagnostic
  # on stderr next to a complete-looking artefact is how a refusal becomes
  # advisory.
  if (bad)
    exit 1;
  for (i = 1; i < lineno; i++)
    {
      ret = parse_line(lines[i], "NEXT_PASS");
      if (ret)
	{
	  # Set pass_name argument, an optional with_arg argument
	  pass_name = args[1];
	  num_args = 0;
	  while (args[num_args + 2])
	    num_args++;

	  # Set pass_final_counts
	  if (pass_name in pass_final_counts)
	    pass_final_counts[pass_name]++;
	  else
	    pass_final_counts[pass_name] = 1;

	  pass_num = pass_final_counts[pass_name];

	  # Print call expression with extra pass_num argument
	  printf "%s", prefix;
	  if (num_args > 0)
	    {
	      printf "NEXT_PASS_WITH_ARG";
	      if (num_args != 1)
	        printf "S";
	    }
	  else
	    printf "NEXT_PASS";
	  printf " (%s, %s", pass_name, pass_num;
	  for (j = 0; j < num_args; j++)
	    printf ",%s", args[j+2];
	  printf ")%s\n", postfix;

	  continue;
	}

      ret = parse_line(lines[i], "PUSH_INSERT_PASSES_WITHIN");
      if (ret)
	{
	  pass_name = args[1];

	  pass_num = pass_final_counts[pass_name];
	  if (!pass_num)
	    {
	      print "ERROR: Can't locate instance of the pass mentioned in " pass_name;
	      exit 1;
	    }

	  printf "%s", prefix;
	  printf "PUSH_INSERT_PASSES_WITHIN";
	  printf " (%s, %s", pass_name, pass_num;
	  printf ")%s\n", postfix;

	  continue;
	}

      print lines[i];
    }
  # print out the #undefs
  print "#undef INSERT_PASSES_AFTER"
  print "#undef PUSH_INSERT_PASSES_WITHIN"
  print "#undef POP_INSERT_PASSES"
  print "#undef NEXT_PASS"
  print "#undef NEXT_PASS_WITH_ARG"
  print "#undef NEXT_PASS_WITH_ARGS"
  print "#undef TERMINATE_PASS_LIST"
}

# Local Variables:
# mode:awk
# c-basic-offset:8
# End:
