#! /bin/sh

# Copyright (C) 2026 Free Software Foundation, Inc.
# This file is part of GCC.
#
# GCC is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3, or (at your option) any later version.
#
# GCC is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with GCC; see the file COPYING3.  If not see
# <http://www.gnu.org/licenses/>.

# Build the multi-target manifest and everything derived from it, one stanza
# per configured target.
#
# Why this is a script and not more shell in gcc/configure.ac: configure.ac is
# about the host and the build machine.  A loop that sources config.gcc once
# per target and writes per-target make rules is target configuration, and it
# had grown to a third of the file.  Nothing here probes the host, so nothing
# here needs autoconf; it needs a shell, config.sub, config.gcc and awk.
#
# Usage:
#
#   . ${srcdir}/gen-target-manifest.sh
#   gcc_gen_target_manifest || AC_MSG_ERROR([... ${gcc_mt_fatal}])
#
# This one is SOURCED, where gen-multilib-data.sh is run.  It has to be:
# config.gcc reads some seventy of configure's own `enable_*' and `with_*'
# variables -- `enable_multilib', `enable_threads', `with_arch', ... -- and
# configure does not export them.  A child process would source config.gcc
# with those unset and get a different, silently plausible answer for every
# target that consults one.  Sourcing keeps the loop in configure's shell,
# which is exactly where the single-target `. ${srcdir}/config.gcc' above it
# already runs.
#
# Inputs, all already set by configure at the point of the call:
#
#   srcdir                  gcc source directory
#   AWK                     awk to use
#   gcc_manifest_targets    the raw target list, primary target included.  It
#                           is canonicalised and deduplicated here, so the
#                           caller does not have to.
#
# Writes, in the current directory:
#
#   multi-target.manifest           one blank-line-separated stanza per target
#   multi-target-common.mk          per-target make rules
#   multi-target-common.h           the common-hook table registry
#   multi-target-spec-functions.h   the driver spec-function table registry
#
# and leaves set, in the caller's shell: gcc_manifest_targets (now
# canonicalised), gcc_all_common_objects, gcc_all_common_symbols,
# gcc_all_spec_fn_objects, gcc_all_target_gtfiles.
#
# On failure it sets gcc_mt_fatal to the reason and returns 1.  It does not
# exit and does not print: the caller owns the diagnostic, so that a half
# written manifest cannot be mistaken for a source bug.

gcc_gen_target_manifest () {

gcc_mt_fatal=

if test x"${gcc_manifest_targets}" = x; then
  gcc_mt_fatal="no targets given"
  return 1
fi

gcc_all_common_objects=
gcc_all_common_symbols=
gcc_all_target_gtfiles=
gcc_common_mk=multi-target-common.mk
echo "# Generated by configure: one rule per target's common hook table." > ${gcc_common_mk}
# Registry of the tables, as data for common/common-target-select.cc.
gcc_common_ext=multi-target-common.ext
gcc_common_ent=multi-target-common.ent
: > ${gcc_common_ext}
: > ${gcc_common_ent}
# The same two pieces for the driver's spec-function tables.
gcc_all_spec_fn_objects=
gcc_sf_ext=multi-target-spec-functions.ext
gcc_sf_ent=multi-target-spec-functions.ent
: > ${gcc_sf_ext}
: > ${gcc_sf_ent}
gcc_target_manifest=multi-target.manifest
: > ${gcc_target_manifest}
gcc_mt_err=conftest.mterr

#
# Canonicalise the list, and deduplicate it once canonical.
gcc_mt_canon=
for gcc_mt in ${gcc_manifest_targets}; do
  gcc_mt_c=`${srcdir}/../config.sub ${gcc_mt} 2> ${gcc_mt_err}`
  if test x"${gcc_mt_c}" = x; then
    gcc_mt_fatal="${gcc_mt} is not a recognised target name"
    return 1
  fi
  gcc_mt_seen=no
  for gcc_mt_have in ${gcc_mt_canon}; do
    if test x"${gcc_mt_have}" = x"${gcc_mt_c}"; then
      gcc_mt_seen=yes
    fi
  done
  if test x"${gcc_mt_seen}" = xno; then
    gcc_mt_canon="${gcc_mt_canon} ${gcc_mt_c}"
  fi
done
gcc_manifest_targets=${gcc_mt_canon}

for gcc_mt in ${gcc_manifest_targets}; do
  # The with_* group no longer needs clearing here:
  gcc_mt_data=`
    target=${gcc_mt}
    tm_defines= cpu_type= target_cpu_default=
    tm_file= tm_p_file= tmake_file=
    extra_objs= extra_options= extra_headers= c_target_objs=
    extra_gcc_objs=
    out_file= md_file= target_gtfiles=
    common_out_file= target_has_targetm_common= dwarf2= extra_modes=
    TM_MULTILIB_CONFIG=
    . ${srcdir}/config.gcc 2> ${gcc_mt_err} > /dev/null || exit 1
    # config.gcc leaves these unset for most targets; the primary target gets
    # them defaulted just below, ...
    test x"${tm_file}" = x && tm_file=${cpu_type}/${cpu_type}.h
    test x"${md_file}" = x && md_file=${cpu_type}/${cpu_type}.md
    test x"${out_file}" = x && out_file=${cpu_type}/${cpu_type}.cc
    echo "target ${gcc_mt}"
    echo "cpu_type ${cpu_type}"
    # This targets own CPU/ABI defaults, as name=value pairs whose names are
    # the OPTION_DEFAULT_SPECS ...
    echo "option_defaults ${target_option_defaults}"
    # Target properties cc1 needs that are decided by the triple, not probed.
    echo "decimal_float ${target_decimal_float}"
    echo "decimal_bid_format ${target_decimal_bid_format}"
    # Which common-hook table this target uses, and the name it will be
    # compiled under.
    echo "common_out_file ${common_out_file}"
    # Use $( ) here, not backticks.
    echo "common_out_symbol targetm_common_$(basename ${common_out_file} .cc | sed 's/-/_/g')"
    echo "tm_file ${tm_file}"
    echo "tm_p_file ${tm_p_file}"
    echo "tmake_file ${tmake_file}"
    # Which of those fragments actually exist.
    mt_tmake_present=
    for mt_tf in ${tmake_file}; do
      if test -f ${srcdir}/config/${mt_tf}; then
	mt_tmake_present="${mt_tmake_present} ${mt_tf}"
      fi
    done
    echo "tmake_file_present ${mt_tmake_present}"
    echo "extra_objs ${extra_objs}"
    # The objects this target needs linked into the DRIVER rather than into
    # cc1: config/<cpu>/driver-<cpu>.cc and friends.  gcc/configure substitutes
    # @extra_gcc_objs@ from config.host alone -- the HOST's driver-<cpu>.o for
    # -march=native -- because gcc/configure.ac no longer runs config.gcc for a
    # target, so the target side of this variable was reaching the build as the
    # empty string for every back end.  A driver holding N back ends needs the
    # UNION of their extra_gcc_objs, and only a per-target record can supply
    # it; see gen-multi-target-md.awk's MT_GCC_OBJS_<cpu>.
    echo "extra_gcc_objs ${extra_gcc_objs}"
    # The C-family target objects.  NOTE FOR ANYONE EDITING THIS BLOCK: it is
    # inside a command substitution, so an apostrophe here truncates the whole
    # stanza and the manifest comes out EMPTY, with configure still exiting 0.
    # That is not hypothetical; it happened while this line was being added.
    #
    # The c_target_objs configure sets is the PRIMARY target alone, and
    # gcc/Makefile.in builds C_TARGET_OBJS from it.  That is why
    # ix86_target_macros is the only TARGET_CPU_CPP_BUILTINS implementation a
    # multi-target cc1 contains, and why c-cppbuiltin.o -- a SHARED translation
    # unit -- carries an undefined reference to it whatever target is selected.
    # Recorded per target here so the build can compile each back end own
    # <cpu>-c.cc against that back end headers.
    echo "c_target_objs ${c_target_objs}"
    echo "extra_options ${extra_options}"
    echo "out_file ${out_file}"
    echo "md_file ${md_file}"
    # The back-end sources gengtype must scan for GTY markers.  gengtype makes
    # ONE pass over a global GTFILES and names its output after the source
    # file (gt-arm.h from config/arm/arm.cc), so unlike the insn-* generators
    # this needs a union, not a rule per back end -- the names cannot collide.
    # Recorded here because configure's own ${target_gtfiles} is the PRIMARY
    # target's alone, which is why gt-<cpu>.h had no rule for anyone else.
    echo "target_gtfiles ${target_gtfiles}"
    # The header list this target's tm.h is built from, in the same form the
    # single-target path uses.
    mt_tm_file="${tm_file} initfini-array.h"
    if test x"${dwarf2}" = xyes; then
      mt_tm_file="${mt_tm_file} tm-dwarf2.h"
    fi
    mt_tm_file="${mt_tm_file} defaults.h"

    mt_tm_include_list="options.h insn-constants.h"
    for mt_f in ${mt_tm_file}; do
      case ${mt_f} in
	./* ) mt_tm_include_list="${mt_tm_include_list} $(echo ${mt_f} | sed 's/^..//')" ;;
	defaults.h ) mt_tm_include_list="${mt_tm_include_list} ${mt_f}" ;;
	* ) mt_tm_include_list="${mt_tm_include_list} config/${mt_f}" ;;
      esac
    done
    echo "tm_include_list ${mt_tm_include_list}"
    echo "tm_defines ${tm_defines}"
    # The value TARGET_CPU_DEFAULT must have in this target's tm.h.  Without it
    # a back end that reads the macro -- nds32 does -- does not compile.
    echo "target_cpu_default ${target_cpu_default}"
    # This back end's extra machine modes.
    echo "extra_modes ${extra_modes}"
    # Headers this target's tm.h includes that no source tree contains:
    mt_tm_gen_headers=
    for mt_f in ${tm_file}; do
      case ${mt_f} in
	./* ) mt_tm_gen_headers="${mt_tm_gen_headers} $(echo ${mt_f} | sed 's/^..//')" ;;
      esac
    done
    echo "tm_generated_headers ${mt_tm_gen_headers}"
    #
    # The multilib set is NOT a config.gcc variable:
    echo "tm_multilib_config ${TM_MULTILIB_CONFIG}"
  ` || {
    # Read the message here, not in the diagnostic's argument:
    gcc_mt_msg=`tr '\n' ' ' < ${gcc_mt_err}`
    gcc_mt_fatal="config.gcc failed for ${gcc_mt}: ${gcc_mt_msg}"
    return 1
  }
  echo "${gcc_mt_data}" >> ${gcc_target_manifest}
  echo "" >> ${gcc_target_manifest}

  # Collect each target's common-hook table so the build can compile all of
  # them.
  gcc_mt_cof=`echo "${gcc_mt_data}" | sed -n 's/^common_out_file //p'`
  gcc_mt_sym=`echo "${gcc_mt_data}" | sed -n 's/^common_out_symbol //p'`
  gcc_mt_obj=`basename ${gcc_mt_cof} .cc`.o
  gcc_mt_base=`basename ${gcc_mt_cof} -common.cc`
  gcc_mt_incl=`echo "${gcc_mt_data}" | sed -n 's/^tm_include_list //p'`
  # cpu_type, not the -common.cc base: the t-<cpu>-headers fragments are named
  # after cpu_type, which is the key gen-multi-target-md.awk includes them by.
  gcc_mt_cpu=`echo "${gcc_mt_data}" | sed -n 's/^cpu_type //p'`
  gcc_mt_tmdef=`echo "${gcc_mt_data}" | sed -n 's/^tm_defines //p'`
  gcc_mt_eopts=`echo "${gcc_mt_data}" | sed -n 's/^extra_options //p'`
  # This target's tm.h must pull in this target's options.h, not the generic
  # one:
  gcc_mt_md=`echo "${gcc_mt_data}" | sed -n 's/^md_file //p'`
  # cpu_type, not the -common.cc base.  options-<X>.h and insn-constants-<X>.h
  # are per BACK END: they come from the .opt files and the .md, neither of
  # which has anything to do with which common-hook file the target shares.
  # The two names coincide for 45 of the 48 back ends and come apart for the
  # three that share default-common.cc (ft32, moxie, rl78); keying on the
  # common file dropped exactly those three.
  gcc_mt_incl=`echo "${gcc_mt_incl}" | sed -e "s|^options\.h|options-${gcc_mt_cpu}.h|" -e "s|insn-constants\.h|insn-constants-${gcc_mt_cpu}.h|"`
  # config.gcc sets this per target and some back ends' tm.h reads it (nds32
  # builds its default ISA out ...
  gcc_mt_tcd=`echo "${gcc_mt_data}" | sed -n 's/^target_cpu_default //p'`
  # Union the gengtype inputs across every configured target.  Deduplicated
  # because two triples of one back end name the same files, and gengtype
  # given a file twice emits its gt- header twice.
  gcc_mt_gtf=`echo "${gcc_mt_data}" | sed -n 's/^target_gtfiles //p'`
  # A back end's MAIN source is not in target_gtfiles: config.gcc lists only
  # the extra files, and gcc/Makefile.in picks up the main one as the singular
  # $(out_file) -- the primary target's, which is why gt-i386.h was the only
  # back-end gt- header a multi-target build produced.  Union it here too.
  gcc_mt_gtf="${gcc_mt_gtf} \$(srcdir)/config/`echo "${gcc_mt_data}" | sed -n 's/^out_file //p'`"
  # ...AND NEITHER IS THE BACK END'S OWN tm.h CHAIN, which is where SIXTEEN of
  # the thirty-four `struct GTY(()) machine_function' definitions live --
  # aarch64, arm, avr, c6x, epiphany, gcn, i386, ia64, loongarch, mips, mmix,
  # nds32, nvptx, pa, rs6000, s390.  gcc/Makefile.in reaches those through
  # $(tm_file_list), which is the PRIMARY target's chain and nobody else's, so
  # gengtype never saw aarch64's declaration at all.
  #
  # Measured before this line existed, in a two-back-end build: gtyp-input.list
  # named config/i386/i386.h and did NOT name config/aarch64/aarch64.h, and
  # `gt_ggc_mx_machine_function' walked i386's three fields for both bases.
  # That is worth separating from the collision it looks like: aarch64's GC
  # data was not being OVERWRITTEN by i386's, it was INVISIBLE.  A per-base
  # namespace in gengtype fixes nothing for a definition gengtype never reads,
  # which is why both halves had to land together.
  #
  # Only entries naming a back end's own directory are added.  The rest of a
  # tm_file chain (elfos.h, linux.h, glibc-stdint.h) is shared and already
  # reaches GTFILES; adding it again would list one file under two spellings.
  # EVERY entry, not only the ones naming this back end's own directory.  The
  # first draft added only `*/*' and left the shared ones (elfos.h, linux.h,
  # glibc-stdint.h) to $(tm_file_list) -- and $(tm_file_list) is one target's
  # chain, so the primary's own headers then arrived twice.  gengtype refused
  # BY NAME, nine times: `config/i386/i386.h specified more than once for
  # language (all)'.  That is the check working, and the answer is not to
  # filter the duplicate out but to stop having a privileged chain at all:
  # gcc/Makefile.in no longer lists $(tm_file_list), and this union is the
  # single authority for which target headers gengtype reads.
  #
  # A `./' PREFIX MEANS THE BUILD DIRECTORY, NOT THE SOURCE TREE, and those
  # entries are skipped.  config.gcc writes `./gcn-device-macros.h' and
  # `./sysroot-suffix.h' into tm_file for headers a tmake_file GENERATES; they
  # are handled a few lines below as tm_generated_headers.  Prefixing them with
  # $(srcdir)/config/ names a file that does not exist and cannot be built, and
  # make says so -- `No rule to make target
  # .../gcc/config/./gcn-device-macros.h, needed by s-gtype'.  It did not show
  # up on the two-back-end pair, because neither i386 nor aarch64 generates a
  # tm.h fragment; it showed up the moment gcn was configured.
  for gcc_mt_tmf in `echo "${gcc_mt_data}" | sed -n 's/^tm_file //p'`; do
    case "${gcc_mt_tmf}" in
      ./*) continue ;;
    esac
    gcc_mt_gtf="${gcc_mt_gtf} \$(srcdir)/config/${gcc_mt_tmf}"
  done
  for gcc_mt_f in ${gcc_mt_gtf}; do
    case " ${gcc_all_target_gtfiles} " in
      *" ${gcc_mt_f} "*) ;;
      *) gcc_all_target_gtfiles="${gcc_all_target_gtfiles} ${gcc_mt_f}" ;;
    esac
  done
  # The same treatment for the headers a target's tmake_file would generate
  # into the build directory.
  gcc_mt_genh=`echo "${gcc_mt_data}" | sed -n 's/^tm_generated_headers //p'`
  gcc_mt_genh_files=
  for gcc_mt_h in ${gcc_mt_genh}; do
    gcc_mt_hb=`basename ${gcc_mt_h} .h`
    gcc_mt_incl=`echo "${gcc_mt_incl}" | sed -e "s|\\([ ]\\)${gcc_mt_hb}\\.h|\\1${gcc_mt_hb}-${gcc_mt_cpu}.h|g"`
    gcc_mt_genh_files="${gcc_mt_genh_files} ${gcc_mt_hb}-${gcc_mt_cpu}.h"
  done
  # gcc_mt_eopts is deliberately NOT turned into a make rule here.  It is read
  # back out of the manifest by the union pass after this loop; see there.
  #
  # *** TWO DEDUPLICATIONS, ON TWO DIFFERENT KEYS, AND THAT IS THE POINT ***
  #
  # The block below is keyed on cpu_type, because what it emits -- this back
  # end's insn-constants, its generated headers and its tm-<base>.h -- is per
  # BACK END.  The block after it is keyed on the common-hook OBJECT, because
  # what that emits is one <x>-common.o per common file.  These were a single
  # dedup on the object, and 45 of the 48 back ends never noticed: cpu_type
  # and the -common.cc base name are the same string for all of them.
  #
  # ft32, moxie and rl78 are the three where they are not.  All three say
  # `common_out_file default-common.cc, so all three fell inside the
  # `!= default guard and got NO insn-constants-<base>.h and NO tm-<base>.h
  # -- while the manifest they were written from still lists them as back
  # ends, gen-multi-target-md.awk still maps their five triples to bases
  # ft32/moxie/rl78 in MT_OPTION_TARGET_BASES, and the options union pass
  # after this loop still counts 48.  Sharing a common-hook file says nothing
  # whatever about a back end's .md, its .opt files or its headers.
  case " ${gcc_all_cpu_bases} " in
    *" ${gcc_mt_cpu} "*) ;;
    *) gcc_all_cpu_bases="${gcc_all_cpu_bases} ${gcc_mt_cpu}"
       # This back end's own options header is NOT emitted here.
       printf 'insn-constants-%s.h: build/genconstants$(build_exeext) $(srcdir)/config/%s\n\t$(RUN_GEN) build/genconstants$(build_exeext) $(srcdir)/config/%s > $@\n\n' \
         "${gcc_mt_cpu}" "${gcc_mt_md}" "${gcc_mt_md}" >> ${gcc_common_mk}
       #
       # The build-directory headers this target's tm.h includes, holding
       # multilib-derived spec macros -- ...
       for gcc_mt_h in ${gcc_mt_genh_files}; do
         case ${gcc_mt_h} in
           *sysroot-suffix*)
             printf '%s: multi-target.manifest multi-target.multilib $(srcdir)/gen-sysroot-suffix.sh\n\t$(SHELL) $(srcdir)/gen-sysroot-suffix.sh %s multi-target.manifest multi-target.multilib $(srcdir) > $@\n\n' \
               "${gcc_mt_h}" "${gcc_mt}" >> ${gcc_common_mk}
             ;;
           *)
             # The rest are headers a config/<cpu>/t-<cpu>-headers fragment already
             # generates under its plain ...
             #
             # *** The `cp' below is only correct while the PLAIN name has a
             # real rule, and the only thing that gives it one in a
             # multi-target build is config/<cpu>/t-<cpu>-headers, which
             # gen-multi-target-md.awk includes unconditionally.  Without the
             # fragment the plain name is whatever the last single-target
             # build left in the directory, and `cp' propagates that stale
             # file into tm-<base>.h without a word.  That is exactly how
             # every arm spec file came to be generated against a stale
             # arm-cpu.h: the rules lived in t-arm, which is included only
             # when arm is PRIMARY, so no other build ever regenerated it.
             #
             # So refuse, loudly, rather than emit a rule that reads a file
             # nothing writes.  A back end reaching here without a fragment
             # is not misconfigured by the user; it means whoever added it
             # has a t-<cpu>-headers split left to do.
             gcc_mt_horig=`echo "${gcc_mt_h}" | sed "s/-${gcc_mt_cpu}\\.h\$/.h/"`
             if test -f ${srcdir}/config/${gcc_mt_cpu}/t-${gcc_mt_cpu}-headers; then :; else
               gcc_mt_fatal="${gcc_mt} needs ${gcc_mt_h}, which is copied from\
 the generated ${gcc_mt_horig}, but config/${gcc_mt_cpu}/t-${gcc_mt_cpu}-headers\
 does not exist.  Only that fragment gives ${gcc_mt_horig} a rule in a\
 multi-target build; without it the copy would silently propagate whatever\
 stale ${gcc_mt_horig} happens to be in the build directory.  Split the rules\
 that generate ${gcc_mt_horig} out of config/${gcc_mt_cpu}/t-${gcc_mt_cpu} into\
 config/${gcc_mt_cpu}/t-${gcc_mt_cpu}-headers, the way\
 config/arm/t-arm-headers and config/loongarch/t-loongarch-headers already do."
               return 1
             fi
             printf '%s: %s\n\tcp $< $@\n\n' \
               "${gcc_mt_h}" "${gcc_mt_horig}" >> ${gcc_common_mk}
             ;;
         esac
       done
       # INSN_BASE: mkconfig.sh needs the back end told to it rather than
       # read off the output name.  Here the two coincide, but stating it
       # keeps this call site and the per-triple one in
       # gen-multi-target-md.awk the same shape, and mkconfig.sh now refuses
       # a tm-*.h without it.
       printf 'tm-%s.h: options-%s.h insn-constants-%s.h%s Makefile\n\tTARGET_CPU_DEFAULT="%s" HEADERS="%s" DEFINES="%s" \\\n\t  INSN_BASE="%s" $(SHELL) $(srcdir)/mkconfig.sh tm-%s.h\n\n' \
         "${gcc_mt_cpu}" "${gcc_mt_cpu}" "${gcc_mt_cpu}" "${gcc_mt_genh_files}" "${gcc_mt_tcd}" "${gcc_mt_incl}" "${gcc_mt_tmdef}" "${gcc_mt_cpu}" "${gcc_mt_cpu}" >> ${gcc_common_mk}
       ;;
  esac
  case " ${gcc_all_common_objects} " in
    *" ${gcc_mt_obj} "*) ;;
    *) gcc_all_common_objects="${gcc_all_common_objects} ${gcc_mt_obj}"
       gcc_all_common_symbols="${gcc_all_common_symbols} ${gcc_mt_sym}"
       # One rule per object. A pattern rule cannot serve here:
       if test x"${gcc_mt_base}" != xdefault; then
         printf '%s: $(srcdir)/common/config/%s tm-%s.h\n\t$(COMPILE) -DMULTI_TARGET_SUPPLY_TU=1 -DTARGETM_COMMON_SYMBOL=%s $<\n\t$(POSTCOMPILE)\n\n' \
           "${gcc_mt_obj}" "${gcc_mt_cof}" "${gcc_mt_base}" "${gcc_mt_sym}" >> ${gcc_common_mk}
         # This back end's driver spec functions, from the same tm-<base>.h.
         gcc_mt_tmflag="-DTM_H_FILE='\"tm-${gcc_mt_base}.h\"'"
         printf 'spec-functions-%s.o: $(srcdir)/spec-functions.cc tm-%s.h $(GCC_H)\n\t$(COMPILE) -DMULTI_TARGET_SUPPLY_TU=1 %s -DSPEC_FUNCTIONS_SYMBOL=extra_spec_functions_%s $(srcdir)/spec-functions.cc\n\t$(POSTCOMPILE)\n\n' \
           "${gcc_mt_base}" "${gcc_mt_base}" "${gcc_mt_tmflag}" "${gcc_mt_base}" >> ${gcc_common_mk}
         gcc_all_spec_fn_objects="${gcc_all_spec_fn_objects} spec-functions-${gcc_mt_base}.o"
         printf 'extern const struct spec_function extra_spec_functions_%s[];\n' \
           "${gcc_mt_base}" >> ${gcc_sf_ext}
       else
         printf '%s: $(srcdir)/common/config/%s\n\t$(COMPILE) -DTARGETM_COMMON_SYMBOL=%s $<\n\t$(POSTCOMPILE)\n\n' \
           "${gcc_mt_obj}" "${gcc_mt_cof}" "${gcc_mt_sym}" >> ${gcc_common_mk}
       fi
       printf 'extern struct gcc_targetm_common %s;\n' "${gcc_mt_sym}" >> ${gcc_common_ext}
       ;;
  esac
  # One entry per target, not per object:
  printf '  TARGETM_COMMON_ENTRY ("%s", %s) \\\n' "${gcc_mt}" "${gcc_mt_sym}" >> ${gcc_common_ent}
  # And one spec-function entry per target, for the same reason.
  if test x"${gcc_mt_base}" != xdefault; then
    printf '  SPEC_FUNCTIONS_ENTRY ("%s", extra_spec_functions_%s) \\\n' \
      "${gcc_mt}" "${gcc_mt_base}" >> ${gcc_sf_ent}
  else
    printf '  SPEC_FUNCTIONS_ENTRY ("%s", spec_functions_empty) \\\n' \
      "${gcc_mt}" >> ${gcc_sf_ent}
  fi
done
rm -f ${gcc_mt_err}

#
#
#
# The options header of a back end, built from the UNION of its triples'
# extra_options.
${AWK} '
  # Manifest stanzas are blank-line separated `key value...` lines.
  #
  # KEYED ON cpu_type, NOT ON common_out_file.  Every other per-back-end
  # artefact is named after cpu_type -- gen-multi-target-md.awk builds
  # mt_bases and mt_base_of from it, so tm-<cpu>.h depends on
  # options-<cpu>.h and multi-target-options.h declares cl_options_<cpu>
  # for exactly that set.  Deriving the base from common_out_file agrees
  # with cpu_type for 45 of the 48 back ends and disagrees for the three
  # that have no per-back-end common file: ft32, moxie and rl78 all say
  # `common_out_file default-common.cc.  Those were dropped here -- the
  # loop below used to skip base "default", because the name collides
  # across every back end that shares that file -- and they were dropped
  # ONLY here, so multi-target-options.h still declared cl_options_ft32
  # and still put it in MT_OPTION_TABLES.  All three have real .opt files
  # (ft32/ft32.opt, moxie/moxie.opt, rl78/rl78.opt), so this is not a set
  # of back ends without options; it is three back ends whose options were
  # requested by one generator and never emitted by the other.
  /^cpu_type / {
    base = $2
    next
  }
  /^extra_options / {
    for (i = 2; i <= NF; i++)
      opt[i] = $i
    n = NF
    next
  }
  /^$/ { flush() }
  END { flush() }

  function flush(   i, f) {
    # Every stanza has a cpu_type, so an empty base means the stanza was
    # malformed rather than that this back end has no options.
    if (base != "") {
      for (i = 2; i <= n; i++) {
	f = opt[i]
	# Order is preserved and duplicates dropped: opt-gather.awk is fed
	# each file once, and a file listed twice would be gathered twice.
	if (!((base SUBSEP f) in seen)) {
	  seen[base SUBSEP f] = 1
	  files[base] = files[base] " $(srcdir)/config/" f
	}
	# ... and the same files unioned across ALL back ends.
	if (!(f in seenall)) {
	  seenall[f] = 1
	  allfiles = allfiles " $(srcdir)/config/" f
	}
      }
      if (!(base in emitted)) {
	emitted[base] = 1
	order[++nbase] = base
      }
    }
    base = ""; n = 0
  }

  END {
    # The .opt files of every configured back end.  gcc/Makefile.in feeds this to
    # opt-gather.awk to build optionlist-vocab, the union of option NAMES.
    printf "MT_OPT_UNION_FILES =%s\n\n", allfiles
    for (i = 1; i <= nbase; i++) {
      b = order[i]
      # This back end own records, PLUS a placeholder for every name in the
      # vocabulary it does not declare.
      printf "optionlist-%s: $(lang_opt_files)%s optionlist-vocab $(srcdir)/opt-gather.awk $(srcdir)/opt-functions.awk $(srcdir)/opt-stub.awk\n", b, files[b]
      printf "\tLC_ALL=C; export LC_ALL; \\\n"
      printf "\t$(AWK) -f $(srcdir)/opt-gather.awk $(lang_opt_files)%s > $@.own\n", files[b]
      printf "\t$(AWK) -f $(srcdir)/opt-functions.awk -f $(srcdir)/opt-stub.awk \\\n"
      printf "\t  -v vocab=optionlist-vocab optionlist-vocab $@.own > $@.stub\n"
      printf "\t@echo \"$@: `wc -l < $@.own` own + `wc -l < $@.stub` placeholder records\"\n"
      printf "\tLC_ALL=C; export LC_ALL; \\\n"
      printf "\tcat $@.own $@.stub | sort > $@\n"
      printf "\trm -f $@.own $@.stub\n\n"
      # This back end contribution to the SHARED `struct gcc_options layout.
      # There is one global_options in the compiler and it had the PRIMARY
      # back end layout, while every other back end was compiled against its
      # own options-<base>.h: measured i386 1709 members against aarch64 1861,
      # with an identical leading run of ZERO, so aarch64_override_options
      # read an i386 field, in bounds and with no diagnostic.  See the long
      # note at the top of opth-gen.awk.  Kept as a separate file per back end
      # so the union rule is a concatenation and cannot half-succeed.
      printf "gcc-options-%s.part: optionlist-%s $(srcdir)/opt-functions.awk $(srcdir)/opt-read.awk $(srcdir)/opth-gen.awk\n", b, b
      printf "\t$(AWK) -f $(srcdir)/opt-functions.awk -f $(srcdir)/opt-read.awk \\\n"
      # srcdir: list mode also records what each HeaderInclude header DEFINES,
      # so that every other back end copy of options.h can undefine it.  The
      # `HeaderInclude paths are srcdir-relative and awk runs in the build
      # directory, so it cannot find them otherwise -- and opth-gen.awk
      # refuses rather than scoring an unopenable header as "defines nothing".
      printf "\t  -v list_mode=1 -v union_base=%s -v srcdir=$(srcdir) \\\n", b
      printf "\t  -f $(srcdir)/opth-gen.awk < $< > tmp-gcc-options-%s.part\n", b
      # Every quote below is written \047, not typed.  This whole awk program
      # is inside a single-quoted shell word, so one literal apostrophe ends
      # it and the rest of the program becomes shell -- which is exactly what
      # happened here first time round: configure printed `unterminated
      # string, appended NOTHING to multi-target-common.mk, and carried on to
      # exit 0.  A build directory then quietly lost every options rule.
      printf "\t@grep -q \047^base %s$$\047 tmp-gcc-options-%s.part || { \\\n", b, b
      printf "\t  echo \047gcc-options-%s.part: no \"base %s\" line;\047 >&2; \\\n", b, b
      printf "\t  echo \047  the union would then be taken over the OTHER back ends\047 >&2; \\\n"
      printf "\t  echo \047  and the members of this one would be missing everywhere.\047 >&2; \\\n"
      printf "\t  exit 1; }\n"
      printf "\t$(SHELL) $(srcdir)/../move-if-change tmp-gcc-options-%s.part $@\n\n", b
      union_parts = union_parts " gcc-options-" b ".part"

      printf "options-%s.h: optionlist-%s $(srcdir)/opt-functions.awk $(srcdir)/opt-read.awk $(srcdir)/opth-gen.awk gcc-options-union.list\n", b, b
      printf "\t$(AWK) -f $(srcdir)/opt-functions.awk -f $(srcdir)/opt-read.awk \\\n"
      # A guard of its own. Sharing one guard across the shared options.h and
      # the other 44 made a second ...
      printf "\t  -v guard_name=OPTIONS_%s_H \\\n", toupper(b)
      printf "\t  -v union_file=gcc-options-union.list -v union_base=%s \\\n", b
      printf "\t  -f $(srcdir)/opth-gen.awk < $< > $@\n\n"
      # THE Init() VALUES BELONGING TO THIS BACK END.  See the long note in
      # optc-gen.awk: an Init() argument is a back-end MACRO, so it can only
      # be compiled where the tm.h of that back end is in scope.  options.cc
      # is compiled with the tm.h of the PRIMARY, which is why every member a
      # non-primary back end has and the primary does not was reading zero.
      #
      # THE SOURCE GOES IN mt-<base>/, NOT THE BUILD ROOT, AND THAT IS NOT
      # TIDINESS.  A quoted #include searches the directory of the INCLUDER
      # first; generated into the build root, this file reached the build
      # root tm.h -- the PRIMARY one -- and compiled clean.  mt-<base>/ holds
      # no headers.
      printf "mt-%s/options-init.cc: optionlist-%s $(srcdir)/opt-functions.awk $(srcdir)/opt-read.awk $(srcdir)/optc-gen.awk\n", b, b
      printf "\t@$(mkinstalldirs) mt-%s\n", b
      printf "\t$(AWK) -f $(srcdir)/opt-functions.awk -f $(srcdir)/opt-read.awk \\\n"
      printf "\t  -f $(srcdir)/optc-gen.awk -v init_base=%s \\\n", b
      printf "\t  -v header_name=\"config.h system.h coretypes.h options.h tm.h\" \\\n"
      printf "\t  < $< > tmp-options-init-%s.cc\n", b
      # A generator that fails and exits 0 has happened on this branch; an
      # empty or headers-only file would compile, link, and leave the bug in
      # place with a selector calling a function that does nothing.  The
      # #error that optc-gen.awk emits covers the no-records case; this covers
      # the case where awk wrote nothing at all.
      printf "\t@test `grep -c \047^  opts->x_\047 tmp-options-init-%s.cc` -gt 0 || { \\\n", b
      printf "\t  echo \047mt-%s/options-init.cc: no assignments were generated;\047 >&2; \\\n", b
      printf "\t  echo \047  every Init() value belonging to %s would stay zero.\047 >&2; \\\n", b
      printf "\t  exit 1; }\n"
      printf "\t$(SHELL) $(srcdir)/../move-if-change tmp-options-init-%s.cc $@\n\n", b
      printf "mt-%s/options-init.o: MULTI_TARGET_INC = -I%s-inc\n", b, b
      printf "mt-%s/options-init.o: mt-%s/options-init.cc\n", b, b
      printf "\t@$(mkinstalldirs) mt-%s/$(DEPDIR)\n", b
      # This TU sees that base'\''s tm.h, so it is on the
      # supply side of defaults.h'\''s (c-DATA) redirection and must keep the
      # real macros.  It is not `targetm'\''-renamed, so it cannot carry
      # MULTI_TARGET_TARGETM_BASE (target.h:392 requires that name to be
      # paired with -Dtargetm=).  See the guard at the end of defaults.h.
      printf "\t$(COMPILE) -DMULTI_TARGET_SUPPLY_TU=1 $<\n"
      printf "\t$(POSTCOMPILE)\n\n"
      printf "MT_OPTIONS_INIT_OBJS += mt-%s/options-init.o\n\n", b

      # THE OPTION TABLES THEMSELVES, per back end.
      #
      # NO APOSTROPHES ANYWHERE IN THIS BLOCK.  The whole awk program is one
      # single-quoted shell word, so a lone apostrophe in a comment ends it,
      # and what follows is read as shell.  The damage is not a syntax error
      # at the point of the typo: it terminated the enclosing shell FUNCTION
      # early, so the two completeness checks below moved to top level and
      # stopped guarding anything -- configure then exited 0 having written a
      # multi-target-common.mk with no options rules in it at all.
      #
      # cl_options[] and cl_enums[] were generated once, from the PRIMARY back
      # end optionlist, and thirteen option names are declared by both back
      # ends of a two-target build with different records -- so an aarch64
      # driver validated -mabi= against the i386 calling_abi and answered
      # "valid arguments to -mabi= are: ms sysv".  The vocabulary is unioned
      # so the INDICES agree; the CONTENT cannot be, because merging the
      # argument lists would make lp64 a valid x86 ABI.
      #
      # Compiled per back end for the same reason options-init.cc is: an
      # EnumValue(... Value(AARCH64_ABI_LP64)) is a back-end macro and has to
      # resolve in its own back end tm.h.  A name that resolves to some OTHER
      # configuration definition compiles clean and is wrong.
      printf "mt-%s/options-tables.cc: optionlist-%s $(srcdir)/opt-functions.awk $(srcdir)/opt-read.awk $(srcdir)/optc-gen.awk\n", b, b
      printf "\t@$(mkinstalldirs) mt-%s\n", b
      printf "\t$(AWK) -f $(srcdir)/opt-functions.awk -f $(srcdir)/opt-read.awk \\\n"
      printf "\t  -f $(srcdir)/optc-gen.awk -v tables_base=%s \\\n", b
      printf "\t  -v header_name=\"config.h system.h coretypes.h options.h tm.h\" \\\n"
      printf "\t  < $< > tmp-options-tables-%s.cc\n", b
      # Both tables, by name.  optc-gen.awk emits an #error when the record
      # set is empty, but an awk that dies partway writes a TRUNCATED file
      # with no #error in it -- and a file holding cl_enums but not
      # cl_options links only because some other base supplied the symbol,
      # which is the privileged-primary bug wearing the clothes of a link error.
      printf "\t@for s in cl_options_%s cl_enums_%s cl_enums_%s_count; do \\\n", b, b, b
      printf "\t  grep -q \"^const .*$$s\" tmp-options-tables-%s.cc || { \\\n", b
      printf "\t    echo \"mt-%s/options-tables.cc: $$s was not generated;\" >&2; \\\n", b
      printf "\t    echo \047  the optionlist for this back end did not reach optc-gen.awk.\047 >&2; \\\n"
      printf "\t    exit 1; }; \\\n"
      printf "\tdone\n"
      printf "\t$(SHELL) $(srcdir)/../move-if-change tmp-options-tables-%s.cc $@\n\n", b
      printf "mt-%s/options-tables.o: MULTI_TARGET_INC = -I%s-inc\n", b, b
      printf "mt-%s/options-tables.o: mt-%s/options-tables.cc\n", b, b
      printf "\t@$(mkinstalldirs) mt-%s/$(DEPDIR)\n", b
      # -DMULTI_TARGET_SUPPLY_TU=1, EXACTLY AS options-init.o ABOVE, and it was
      # missing here.  Both objects are compiled per back end, so both see
      # that base tm.h and both are on the supply side of the (c-DATA)
      # redirection at the end of defaults.h.  Without the marker this object
      # is treated as a CONSUMER: its macros are redirected to targetm_cdata
      # and targetm_regs, which are in libbackend.a and are NOT linked by the
      # driver that consumes this object.
      #
      # It was silent for i386 + aarch64 because both of those define
      # MAX_BITS_PER_WORD explicitly.  A base that does not gets defaults.h
      # deriving it from BITS_PER_WORD, which the redirection turns into a
      # run-time load, and the guard at defaults.h refuses BY NAME.  Measured
      # in a 47-back-end build: 36 of 47 bases failed here.  Thirteen back ends
      # spell MAX_BITS_PER_WORD somewhere under their directory, which is close
      # to the eleven survivors but is NOT the same set -- a definition under
      # config/<cpu>/ is not necessarily in the tm.h chain of the triple this
      # build picked -- so the survivor list is quoted as measured, not derived.
      printf "\t$(COMPILE) -DMULTI_TARGET_SUPPLY_TU=1 $<\n"
      printf "\t$(POSTCOMPILE)\n\n"
      # libcommon-target.a, NOT libbackend.a: the driver is the caller that
      # needed this and it links only the former.
      printf "MT_OPTIONS_TABLES_OBJS += mt-%s/options-tables.o\n\n", b
    }

    # The union list itself, and the singular options.h flags that make
    # gcc/Makefile.in use it.  Both are defined ONLY here, so a single-target
    # build -- which never reads this file -- passes no -v union_file at all
    # and every generated options header comes out byte-identical to before.
    printf "MT_OPTIONS_UNION_LIST = gcc-options-union.list\n\n"
    printf "gcc-options-union.list:%s\n", union_parts
    printf "\tcat%s > tmp-gcc-options-union.list\n", union_parts
    # A SHORT list is the failure that would otherwise be silent: opth-gen.awk
    # -U refuses a list that does not name the back end being generated, which
    # catches the case where the missing base is this one, but a list missing
    # some OTHER back end still covers this one and would simply lay out fewer
    # members -- in every header, consistently, and wrongly.
    printf "\t@test `grep -c \047^base \047 tmp-gcc-options-union.list` -eq %d || { \\\n", nbase
    printf "\t  echo \047gcc-options-union.list: expected %d base lines, got\047 \\\n", nbase
    printf "\t       `grep -c \047^base \047 tmp-gcc-options-union.list`; \\\n"
    printf "\t  echo \047  a short list lays out fewer members than some configured\047; \\\n"
    printf "\t  echo \047  back end needs, in every options header, consistently.\047; \\\n"
    printf "\t  exit 1; } >&2\n"
    printf "\t$(SHELL) $(srcdir)/../move-if-change tmp-gcc-options-union.list $@\n\n"
  }
' ${gcc_target_manifest} >> ${gcc_common_mk}

# AN AWK PROGRAM THAT DIES HALFWAY STILL EXITS 0 HERE, because it is the left
# side of a `>>' and awk reports a run-time error on stderr that configure has
# already redirected.  What comes out is a multi-target-common.mk with the
# per-target rules and none of the options block -- which is not a build
# failure either: MT_OPTIONS_UNION_LIST is then simply empty, gcc/Makefile.in
# passes no -v union_file, and every options header is generated for the
# PRIMARY alone.  That is the exact divergence the union exists to remove,
# reinstated silently, by a syntax error in a comment.  It has happened.
#
# So check the output for the one line per back end that the block must
# contain, and fail the configure rather than the build.
#
# IT NAMES THE BACK ENDS, IT DOES NOT JUST COUNT THEM.  This check spent its
# first life reporting "45 options blocks for 48 back ends" and nothing else,
# and the three missing names -- ft32, moxie and rl78 -- had to be recovered by
# hand from the artefact before anyone could tell whether the blocks or the
# expectation were wrong.  A count says a set is the wrong size; a difference
# says which members are gone, and only the second distinguishes "the awk died
# partway" (a contiguous tail is missing) from "these particular back ends are
# being filtered out" (scattered names, which is what it actually was).
awk '$1 == "cpu_type" { print $2 }' ${gcc_target_manifest} | sort -u \
  > ${gcc_common_mk}.want
sed -n 's|^MT_OPTIONS_INIT_OBJS += mt-\(.*\)/options-init\.o$|\1|p' \
  ${gcc_common_mk} | sort -u > ${gcc_common_mk}.have
gcc_mt_bases=`wc -l < ${gcc_common_mk}.want`
gcc_mt_have=`wc -l < ${gcc_common_mk}.have`
gcc_mt_missing=`comm -23 ${gcc_common_mk}.want ${gcc_common_mk}.have | tr '\n' ' '`
gcc_mt_extra=`comm -13 ${gcc_common_mk}.want ${gcc_common_mk}.have | tr '\n' ' '`
rm -f ${gcc_common_mk}.want ${gcc_common_mk}.have
if test x"${gcc_mt_missing}${gcc_mt_extra}" != x; then
  gcc_mt_fatal="multi-target-common.mk has ${gcc_mt_have} options blocks for\
 ${gcc_mt_bases} back ends.  No MT_OPTIONS_INIT_OBJS line for: ${gcc_mt_missing}\
 -- and a back end with no options block does not fail the build, it takes the\
 empty path: no options-<base>.h, no Init() values, and every one of its\
 targets still registered in MT_OPTION_TARGET_BASES.  A line for a back end not\
 in the manifest: ${gcc_mt_extra}.  Either the awk program over\
 ${gcc_target_manifest} did not run to the end, or it is keyed on something\
 other than cpu_type"
  return 1
fi

# The same check for the option TABLES, and it is a separate one on purpose.
# The two blocks are emitted by the same awk program but the tables block comes
# second, so an awk that dies between them leaves a file that passes the check
# above -- and a build with no MT_OPTIONS_TABLES_OBJS at all does not fail
# either: libcommon-target.a is then short of every per-base table and
# multi-target-options-select.cc fails to link on cl_options_<base>.  That is a
# loud failure, but it names a symbol rather than the manifest, three steps
# from the cause.
awk '$1 == "cpu_type" { print $2 }' ${gcc_target_manifest} | sort -u \
  > ${gcc_common_mk}.want
sed -n 's|^MT_OPTIONS_TABLES_OBJS += mt-\(.*\)/options-tables\.o$|\1|p' \
  ${gcc_common_mk} | sort -u > ${gcc_common_mk}.have
gcc_mt_tables=`wc -l < ${gcc_common_mk}.have`
gcc_mt_missing=`comm -23 ${gcc_common_mk}.want ${gcc_common_mk}.have | tr '\n' ' '`
gcc_mt_extra=`comm -13 ${gcc_common_mk}.want ${gcc_common_mk}.have | tr '\n' ' '`
rm -f ${gcc_common_mk}.want ${gcc_common_mk}.have
if test x"${gcc_mt_missing}${gcc_mt_extra}" != x; then
  gcc_mt_fatal="multi-target-common.mk has ${gcc_mt_tables} option-table\
 blocks for ${gcc_mt_bases} back ends.  No MT_OPTIONS_TABLES_OBJS line for:\
 ${gcc_mt_missing}.  A line for a back end not in the manifest:\
 ${gcc_mt_extra}.  multi-target-options-select.cc will fail to link on\
 cl_options_<base> for each of the first set, three steps from the cause"
  return 1
fi

# Assemble the registry header from the two pieces.
{
  echo "/* Generated by configure.  Every configured target's common hook table."
  echo "   Do not edit.  */"
  echo ""
  cat ${gcc_common_ext}
  echo ""
  echo "#define TARGETM_COMMON_TABLES \\"
  cat ${gcc_common_ent}
  echo "  /* end of table */"
} > multi-target-common.h
rm -f ${gcc_common_ext} ${gcc_common_ent}

# The same, for the driver's spec-function tables.
{
  echo "/* Generated by configure.  Every configured target's driver"
  echo "   spec-function table.  Do not edit.  */"
  echo ""
  cat ${gcc_sf_ext}
  echo ""
  echo "#define SPEC_FUNCTIONS_TABLES \\"
  cat ${gcc_sf_ent}
  echo "  /* end of table */"
} > multi-target-spec-functions.h
rm -f ${gcc_sf_ext} ${gcc_sf_ent}

# gcc_manifest_targets, gcc_all_common_objects, gcc_all_common_symbols,
# gcc_all_spec_fn_objects and gcc_all_target_gtfiles are left set for the
# caller to AC_SUBST.
return 0

}
