/* Generate from machine description:
   a series of #define statements, one for each constant named in
   a (define_constants ...) pattern.

   Copyright (C) 1987-2026 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

/* This program does not use gensupport.cc to look at insn patterns -- it
   needs only (define_constants).  It does need ONE thing from the gen*
   common code: whether `unspec_strings' is an array or a pointer has to be
   decided the same way in the header this program writes and in the file
   genenums.cc writes, and gen_multi_target_p () is where that decision
   lives.  The alternative is a second copy of it here, i.e. one name with two
   authorities, which is the failure the whole per-back-end suffix exists to
   prevent.

   THAT DEPENDENCY IS ON gen-target-ns.cc, NOT ON gensupport.cc, AND THE
   DIFFERENCE IS WHAT MAKES A COLD BUILD POSSIBLE.  This file used to include
   gensupport.h, which needs rtl.h, which wants FIRST_PSEUDO_REGISTER, which
   on aarch64 is (LAST_FAKE_REGNUM + 1) out of insn-constants.h -- the very
   file this program exists to write.  make saw the loop and dropped it:

       make[1]: Circular build/genconstants.o <- insn-constants.h dependency
                dropped.
       ./tm.h:41:11: fatal error: insn-constants.h: No such file or directory

   so the branch could only be built in a directory that already had the
   header from some earlier state.  gen-target-ns.h reads no target macro and
   includes no target header, by rule; keep it that way.  */

#include "bconfig.h"
#include "system.h"
#include "coretypes.h"
#include "errors.h"
#include "statistics.h"
#include "vec.h"
#include "read-md.h"
#include "gen-target-ns.h"

/* Called via traverse_md_constants; emit a #define for
   the current constant definition.  */

static int
print_md_constant (void **slot, void *info ATTRIBUTE_UNUSED)
{
  struct md_constant *def = (struct md_constant *) *slot;

  if (!def->parent_enum)
    printf ("#define %s %s\n", def->name, def->value);
  return 1;
}

/* Called via traverse_enums.  Emit an enum definition for
   enum_type *SLOT.  */

static int
print_enum_type (void **slot, void *info ATTRIBUTE_UNUSED)
{
  struct enum_type *def;
  struct enum_value *value;
  char *value_name;

  def = (struct enum_type *) *slot;
  printf ("\nenum %s {", def->name);
  for (value = def->values; value; value = value->next)
    {
      printf ("\n  %s = %s", value->def->name, value->def->value);
      if (value->next)
	putc (',', stdout);
    }
  printf ("\n};\n");

  /* Define NUM_<enum>_VALUES to be the largest enum value + 1.

     On the SINGULAR multi-target run this number is the PRIMARY back end's
     and is wrong for every other one -- measured NUM_UNSPECV_VALUES 114 for
     i386 against aarch64's 40 -- so it must never be used as a bound on
     <enum>_strings, which is a per-back-end table selected at run time.  It
     is emitted anyway, and unchanged, because the middle end still needs a
     compile-time answer to "does this compiler have such an enum at all",
     which is what `#if defined (NUM_<enum>_VALUES)' asks.  The bound is
     <enum>_strings_len, below, which travels with the table.  */
  value_name = ACONCAT (("num_", def->name, "_values", NULL));
  upcase_string (value_name);
  printf ("#define %s %d /* NOT a bound: see %s_strings_len.  */\n",
	  value_name, def->num_values, def->name);

  /* Declare the array that is generated by genenum.  A multi-target build
     declares a POINTER instead: each back end has its own table, in namespace
     insn_<base>, and multi-target-select.cc aims this name at the one in
     force.  Written out here rather than through a macro because
     insn-constants.h is reached by routes that do not include insn-modes.h,
     where GCC_TARGET_TABLE would live.  */
  if (gen_multi_target_p ())
    printf ("extern const char *const *%s_strings;\n", def->name);
  else
    printf ("extern const char *const %s_strings[];\n", def->name);

  /* THE BOUND, and it has to be a run-time value.  genenums derives it from
     the table it has just written (ARRAY_SIZE of that very array), so the
     length cannot drift from the table the way NUM_<enum>_VALUES did: one
     authority, and it is the authority that owns the storage.  Declared for
     the single-target build too, where genenums defines it bare and it is
     simply equal to NUM_<enum>_VALUES -- one spelling at every use site
     rather than an #ifdef at each of them.  */
  printf ("extern int %s_strings_len;\n", def->name);

  return 1;
}

int
main (int argc, const char **argv)
{
  progname = "genconstants";

  noop_reader reader;
  if (!reader.read_md_files (argc, argv, NULL))
    return (FATAL_EXIT_CODE);

  /* Initializing the MD reader has the side effect of loading up
     the constants table that we wish to scan.  */

  puts ("/* Generated automatically by the program `genconstants'");
  puts ("   from the machine description file `md'.  */\n");
  puts ("#ifndef GCC_INSN_CONSTANTS_H");
  puts ("#define GCC_INSN_CONSTANTS_H\n");

  reader.traverse_md_constants (print_md_constant, 0);
  reader.traverse_enum_types (print_enum_type, 0);

  puts ("\n#endif /* GCC_INSN_CONSTANTS_H */");

  if (ferror (stdout) || fflush (stdout) || fclose (stdout))
    return FATAL_EXIT_CODE;

  return SUCCESS_EXIT_CODE;
}
