/* Which back end writes a CUMULATIVE_ARGS, and the shared-code entry points.
   Copyright (C) 2026 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 3, or (at your option) any later
version.

GCC is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#include "config.h"
#include "system.h"
#include "coretypes.h"
#include "tm.h"
#include "rtl.h"
#include "tree.h"
#include "target.h"
#include "diagnostic-core.h"
#include "target-cumargs.h"

/* Declares every configured back end's table and defines TARGETM_CUMARGS_TABLES
   listing them.  Generated by gen-multi-target-md.awk.  */
#include "multi-target-cumargs.h"

#define TARGETM_CUMARGS_ENTRY(NAME, SYM) { NAME, &SYM },
const struct target_cumargs_entry targetm_cumargs_registry[] = {
  TARGETM_CUMARGS_TABLES
  { NULL, NULL }
};
#undef TARGETM_CUMARGS_ENTRY

/* NULL, not the primary's table.  See target-regs.h for the argument at
   length: a default here compiles aarch64 arguments with i386's
   argument-passing state, in bounds and with no diagnostic.  */
const struct target_cumargs_desc *targetm_cumargs;

const struct target_cumargs_desc *
target_cumargs_for (const char *base)
{
  for (const struct target_cumargs_entry *e = targetm_cumargs_registry;
       e->name != NULL; e++)
    if (strcmp (e->name, base) == 0)
      return e->cumargs;
  return NULL;
}

/* The shared-code entry points.  Each is one indirection with a by-name check
   in front of it.

   THE CHECK IS NOT DEFENSIVE PROGRAMMING.  These are on the path every
   function compilation takes, and the state they guard against -- no target
   selected -- is reachable: `cc1' without `-ftarget-config=' has no base.
   Without the check the first `->init_args' is a null call, which arrives as
   a SIGSEGV at address 0 and reads as a miscompile rather than as "you did
   not select a target".  */
static const struct target_cumargs_desc *
mt_cumargs (void)
{
  if (targetm_cumargs == NULL)
    internal_error ("no back end has been selected, so there is nothing to "
		    "initialise a %<CUMULATIVE_ARGS%> with; a target must be "
		    "chosen with %<-ftarget-config=%> before any function is "
		    "compiled");
  return targetm_cumargs;
}

void
mt_init_cumulative_args (cumulative_args_t ca, tree fntype, rtx libname,
			 tree fndecl, int n_named_args)
{
  mt_cumargs ()->init_args (ca, fntype, libname, fndecl, n_named_args);
}

void
mt_init_cumulative_incoming_args (cumulative_args_t ca, tree fntype,
				  rtx libname)
{
  mt_cumargs ()->init_incoming_args (ca, fntype, libname);
}

void
mt_init_cumulative_libcall_args (cumulative_args_t ca, machine_mode outmode,
				 rtx fun, int nargs)
{
  mt_cumargs ()->init_libcall_args (ca, outmode, fun, nargs);
}

int
mt_call_pops_args (cumulative_args_t ca)
{
  return mt_cumargs ()->call_pops_args (ca);
}

void
mt_override_abi_format (tree fndecl)
{
  mt_cumargs ()->override_abi_format (fndecl);
}

/* ------------------------------------------------------------------------
   THE FRAME AND ARGUMENT-REGISTER ANSWERS; see target-frame.h.

   `targetm_frame' is set beside `targetm_cumargs' by whoever selects a base,
   and is NOT derived from it here, so that a base selected for its argument
   accumulator but never given a frame table fails by name rather than
   answering with a stale pointer.  */
const struct target_frame_desc *targetm_frame;

static const struct target_frame_desc *
mt_frame (void)
{
  if (targetm_frame == NULL)
    internal_error ("no back end has been selected, so the frame layout of "
		    "the function being compiled is unknown; a target must be "
		    "chosen with %<-ftarget-config=%> before any function is "
		    "compiled");
  return targetm_frame;
}

int
mt_stack_boundary (void)
{
  return mt_frame ()->stack_boundary ();
}

int
mt_preferred_stack_boundary (void)
{
  return mt_frame ()->preferred_stack_boundary ();
}

unsigned int
mt_stack_slot_alignment (tree type, machine_mode mode, unsigned int align)
{
  return mt_frame ()->stack_slot_alignment (type, mode, align);
}

unsigned int
mt_minimum_alignment (tree exp, machine_mode mode, unsigned int align)
{
  return mt_frame ()->minimum_alignment (exp, mode, align);
}

int
mt_outgoing_reg_parm_stack_space (tree fntype)
{
  return mt_frame ()->outgoing_reg_parm_stack_space (fntype);
}

bool
mt_function_arg_regno_p (int regno)
{
  return mt_frame ()->function_arg_regno_p (regno);
}

/* emit-rtl.cc's two `#ifdef INIT_EXPANDERS' sites, answered by the selected
   back end instead of by whichever base compiled emit-rtl.cc.

   The `has_init_expanders' / `init_expanders' pair is checked against itself
   here, not merely dereferenced.  A back end with nothing to run is a normal
   and common case -- 35 of the 48 are in it -- so a null pointer alone cannot
   be treated as an error; but a null pointer that the base did NOT claim, or
   a claim with no function behind it, is an object built against a different
   version of target-frame.h, and that has exactly one symptom otherwise:
   `cfun->machine' stays null and the back end faults on it much later.  This
   turns that into a diagnostic naming the base.  */
void
mt_init_expanders (void)
{
  const struct target_frame_desc *f = mt_frame ();

  if (f->has_init_expanders != (f->init_expanders != NULL))
    {
      if (f->has_init_expanders)
	internal_error ("back end %qs records that it defines "
			"%<INIT_EXPANDERS%> but supplies no function for it; "
			"its objects and %<target-frame.h%> are from "
			"different builds", f->name);
      else
	internal_error ("back end %qs records that it defines no "
			"%<INIT_EXPANDERS%> yet supplies a function for it; "
			"its objects and %<target-frame.h%> are from "
			"different builds", f->name);
    }

  if (f->init_expanders != NULL)
    f->init_expanders ();
}
