/* Which back end's addressing predicates are in force.
   Copyright (C) 2026 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 3, or (at your option) any later
version.

GCC is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#include "config.h"
#include "system.h"
#include "coretypes.h"
#include "target-addr.h"

/* Declares every configured back end's table and defines TARGETM_ADDR_TABLES
   listing them.  Generated by gen-multi-target-md.awk from
   multi-target.manifest.  */
#include "multi-target-addr.h"

/* Naming every table here is not merely descriptive.  It follows
   target-asm-ops-select.cc and common/common-target-select.cc: an object
   nothing refers to is not pulled out of an archive, so without a reference
   the only table reaching the compiler would be whichever one something else
   happened to mention.  */
#define TARGETM_ADDR_ENTRY(NAME, SYM) { NAME, &SYM },
const struct target_addr_entry targetm_addr_registry[] = {
  TARGETM_ADDR_TABLES
  { NULL, NULL }
};
#undef TARGETM_ADDR_ENTRY

/* The table in force.  Constant-initialised with the address of the primary
   target's table -- a constant expression, so no dynamic initialisation and no
   window in which this is null.

   That matters more here than it does for the assembler directives.
   `base_reg_class ()' is reached from `init_reg_sets_1' and from the register
   allocators, i.e. from code that runs long before any `-ftarget-config='
   selection would have a chance to redirect a pointer initialised at run time.
   A null slot there would be a jump through zero, not a wrong section
   directive.  */
const struct target_addr *targetm_addr = &TARGETM_ADDR_SYMBOL;

const struct target_addr *
target_addr_for (const char *base)
{
  for (const struct target_addr_entry *e = targetm_addr_registry;
       e->name != NULL; e++)
    if (strcmp (e->name, base) == 0)
      return e->addr;
  return NULL;
}
