/* Which back end's per-configuration data is in force.
   Copyright (C) 2026 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 3, or (at your option) any later
version.

GCC is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#include "config.h"
#include "system.h"
#include "coretypes.h"
#include "diagnostic-core.h"
#include "target-cdata.h"

/* Declares every configured back end's refresh function and defines
   TARGETM_CDATA_TABLES listing them.  Generated by gen-multi-target-md.awk.  */
#include "multi-target-cdata.h"

#define TARGETM_CDATA_ENTRY(NAME, SYM) { NAME, SYM },
const struct target_cdata_entry targetm_cdata_registry[] = {
  TARGETM_CDATA_TABLES
  { NULL, NULL }
};
#undef TARGETM_CDATA_ENTRY

/* STARTS AS THE POISON, NOT AS THE PRIMARY'S VALUES.

   Every string field is a self-naming sentinel until `init_targetm_cdata ()'
   runs.  Filling these with the primary's answers instead would be the whole
   bug class this branch exists to remove -- a missed refresh would then be
   correct on the build machine and wrong everywhere else, silently.  Here it
   surfaces as `<target-cdata read before refresh>' appearing where a type name
   or a comment character was expected, which is unmistakable and names
   itself.  */
struct target_cdata targetm_cdata = {
#define TARGET_CDATA_STR(F, M) TARGET_CDATA_POISON_STR,
#define TARGET_CDATA_NUM(T, F, M) (T) TARGET_CDATA_POISON_NUM,
  /* An optional field starts with BOTH slots poisoned.  The flag's poison is
     its own third state rather than `false': `false' is a legitimate answer
     here -- most back ends define none of these macros -- so it must not be
     what an unwritten slot looks like.  */
#define TARGET_CDATA_OPTNUM(T, F, M)					\
  TARGET_CDATA_POISON_FLAG, (T) TARGET_CDATA_POISON_NUM,
  TARGET_CDATA_FIELDS (TARGET_CDATA_STR, TARGET_CDATA_NUM)
  TARGET_CDATA_OPT_FIELDS (TARGET_CDATA_OPTNUM)
#undef TARGET_CDATA_STR
#undef TARGET_CDATA_NUM
#undef TARGET_CDATA_OPTNUM
};

/* NULL until a target is selected; see `init_targetm_cdata'.  */
void (*targetm_cdata_refresh) (struct target_cdata *);

void (*target_cdata_refresh_for (const char *base)) (struct target_cdata *)
{
  for (const struct target_cdata_entry *e = targetm_cdata_registry;
       e->name != NULL; e++)
    if (strcmp (e->name, base) == 0)
      return e->refresh;
  return NULL;
}

void
init_targetm_cdata (void)
{
  /* No fallback, deliberately.  A compiler that has selected no target has no
     per-configuration data, and saying so here is better than answering with
     whichever base happened to be linked first.  The poison the struct still
     holds is the diagnostic if anything does read it.  */
  if (targetm_cdata_refresh == NULL)
    internal_error ("no target configuration was selected, so there is no "
		    "per-configuration target data to install");

  targetm_cdata_refresh (&targetm_cdata);

  /* The refresh must actually have written something.  A refresh function that
     was generated empty -- or one whose macros were the REDIRECTED ones, so
     that it copied the poison back into place -- would otherwise leave the
     compiler running on sentinels and only fail much later, in the assembler
     or in a front end, with no mention of this file.

     EVERY field is checked, from the same list the struct and the refresh
     function are generated from, and the failure NAMES THE FIELD.  Checking
     one representative would be the cheaper thing to write and would report
     success for a struct whose other twenty-two slots were still sentinels --
     a check that can only ever observe the field it was written for is the
     shape this project has been caught by repeatedly.  */
#define TARGET_CDATA_STR(F, M)						\
  if (targetm_cdata.F == NULL						\
      || strcmp (targetm_cdata.F, TARGET_CDATA_POISON_STR) == 0)	\
    internal_error ("the selected back end%'s target-cdata refresh left "	\
		    "%<%s%> unwritten; it was compiled against the "	\
		    "redirected macros rather than its own tm.h", #F);
#define TARGET_CDATA_NUM(T, F, M)					\
  if (targetm_cdata.F == (T) TARGET_CDATA_POISON_NUM)			\
    internal_error ("the selected back end%'s target-cdata refresh left "	\
		    "%<%s%> unwritten; it was compiled against the "	\
		    "redirected macros rather than its own tm.h", #F);
  /* AN OPTIONAL FIELD IS CHECKED IN BOTH DIRECTIONS, and that is the point of
     the shape.  The mandatory check above can only ask "was anything
     written", because every back end has an answer.  Here `absent' is a real
     answer, so a one-sided check would accept the two failures that matter:

       flag still poisoned      -- the refresh never ran for this field, which
				   a plain bool would have shown as a
				   perfectly ordinary `this target has none'.
       absent but value written -- the back end reported no macro and yet
				   produced a number, so something evaluated a
				   macro it does not have.  That can only be
				   the redirection leaking, and it is exactly
				   the silent wrong answer the conversion
				   exists to remove.

     Both name the field.  */
#define TARGET_CDATA_OPTNUM(T, F, M)					\
  if (targetm_cdata.has_##F == TARGET_CDATA_POISON_FLAG)		\
    internal_error ("the selected back end%'s target-cdata refresh left "	\
		    "%<%s%> undecided; it did not say whether this target "	\
		    "defines %<%s%> at all", #F, #M);			\
  if (targetm_cdata.has_##F						\
      && targetm_cdata.F == (T) TARGET_CDATA_POISON_NUM)		\
    internal_error ("the selected back end reports %<%s%> present but left "	\
		    "its value unwritten", #M);				\
  if (!targetm_cdata.has_##F						\
      && targetm_cdata.F != (T) TARGET_CDATA_POISON_NUM)		\
    internal_error ("the selected back end reports %<%s%> absent and yet "	\
		    "wrote a value for it, so a macro it does not define "	\
		    "was evaluated", #M);
  TARGET_CDATA_FIELDS (TARGET_CDATA_STR, TARGET_CDATA_NUM)
  TARGET_CDATA_OPT_FIELDS (TARGET_CDATA_OPTNUM)
#undef TARGET_CDATA_STR
#undef TARGET_CDATA_NUM
#undef TARGET_CDATA_OPTNUM
}
