/* Which back end's register vocabulary is in force.
   Copyright (C) 2026 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 3, or (at your option) any later
version.

GCC is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#include "config.h"
#include "system.h"
#include "coretypes.h"
#include "target-regs.h"

/* Declares every configured back end's table and defines TARGETM_REGS_TABLES
   listing them.  Generated by gen-multi-target-md.awk.  */
#include "multi-target-regs.h"

#define TARGETM_REGS_ENTRY(NAME, SYM) { NAME, &SYM },
const struct target_regs_entry targetm_regs_registry[] = {
  TARGETM_REGS_TABLES
  { NULL, NULL }
};
#undef TARGETM_REGS_ENTRY

/* NULL, not the primary's table.  See target-regs.h: a default here would make
   a compiler that never selected answer i386's register classes and i386's
   register names for every target -- correct on the build machine, wrong
   everywhere else, and with no diagnostic.  `init_reg_sets' checks.  */
const struct target_regs_desc *targetm_regs;

const struct target_regs_desc *
target_regs_for (const char *base)
{
  for (const struct target_regs_entry *e = targetm_regs_registry;
       e->name != NULL; e++)
    if (strcmp (e->name, base) == 0)
      return e->regs;
  return NULL;
}
