/* Which back end's C-family target entry points are in force.
   Copyright (C) 2026 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 3, or (at your option) any later
version.

GCC is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#include "config.h"
#include "system.h"
#include "coretypes.h"
#include "diagnostic-core.h"
#include "target-c-ops.h"
#include "multi-target-select.h"

/* Declares every configured back end's table and defines TARGETM_C_OPS_TABLES
   listing them.  Generated by gen-multi-target-md.awk.  */
#include "multi-target-c-ops.h"

#define TARGETM_C_OPS_ENTRY(NAME, SYM) { NAME, &SYM },
static const struct target_c_ops_entry targetm_c_ops_registry[] = {
  TARGETM_C_OPS_TABLES
  { NULL, NULL }
};
#undef TARGETM_C_OPS_ENTRY

const struct target_c_ops *targetm_c_ops;

const struct target_c_ops *
target_c_ops_for (const char *base)
{
  for (const struct target_c_ops_entry *e = targetm_c_ops_registry;
       e->name != NULL; e++)
    if (strcmp (e->name, base) == 0)
      return e->ops;
  return NULL;
}

/* NO FALLBACK.  Before this branch, `TARGET_CPU_CPP_BUILTINS ()' in the shared
   c-cppbuiltin.o was a direct call into the PRIMARY back end, so a compiler
   asked for another target ran i386's predefines and crashed inside
   `ix86_target_macros_internal' -- with the aarch64 back end otherwise in
   force, having already written `.arch armv8-a'.  Answering with the primary
   here would restore exactly that, so the absence of a selection fails by
   name.  */

/* Resolved on FIRST USE rather than installed by multi_target_select, because
   multi-target-select.o is in libbackend.a and so is linked into lto1, while
   these tables call into c-family and only cc1 has those symbols.  See
   multi-target-select.h.  */

static const struct target_c_ops *
c_ops_in_force (const char *what)
{
  if (targetm_c_ops == NULL)
    {
      const char *base = multi_target_current_base ();

      if (base == NULL)
	internal_error ("%qs was used before a target was selected: no back "
			"end%'s C-family entry points are installed", what);

      targetm_c_ops = target_c_ops_for (base);
      if (targetm_c_ops == NULL)
	internal_error ("back end %qs has no C-family entry-point table; "
			"gen-multi-target-md.awk emits one for every back end "
			"that has objects, so this is a build bug", base);
    }
  return targetm_c_ops;
}

void
target_c_cpu_cpp_builtins (struct cpp_reader *pfile)
{
  c_ops_in_force ("TARGET_CPU_CPP_BUILTINS")->cpu_cpp_builtins (pfile);
}

void
target_c_register_pragmas (void)
{
  c_ops_in_force ("REGISTER_TARGET_PRAGMAS")->register_pragmas ();
}
