/* Which back end writes a CUMULATIVE_ARGS, and the shared-code entry points.
   Copyright (C) 2026 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 3, or (at your option) any later
version.

GCC is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#include "config.h"
#include "system.h"
#include "coretypes.h"
#include "tm.h"
#include "rtl.h"
#include "tree.h"
#include "target.h"
#include "diagnostic-core.h"
#include "target-cumargs.h"

/* Declares every configured back end's table and defines TARGETM_CUMARGS_TABLES
   listing them.  Generated by gen-multi-target-md.awk.  */
#include "multi-target-cumargs.h"

#define TARGETM_CUMARGS_ENTRY(NAME, SYM) { NAME, &SYM },
const struct target_cumargs_entry targetm_cumargs_registry[] = {
  TARGETM_CUMARGS_TABLES
  { NULL, NULL }
};
#undef TARGETM_CUMARGS_ENTRY

/* NULL, not the primary's table.  See target-regs.h for the argument at
   length: a default here compiles aarch64 arguments with i386's
   argument-passing state, in bounds and with no diagnostic.  */
const struct target_cumargs_desc *targetm_cumargs;

const struct target_cumargs_desc *
target_cumargs_for (const char *base)
{
  for (const struct target_cumargs_entry *e = targetm_cumargs_registry;
       e->name != NULL; e++)
    if (strcmp (e->name, base) == 0)
      return e->cumargs;
  return NULL;
}

/* The shared-code entry points.  Each is one indirection with a by-name check
   in front of it.

   THE CHECK IS NOT DEFENSIVE PROGRAMMING.  These are on the path every
   function compilation takes, and the state they guard against -- no target
   selected -- is reachable: `cc1' without `-ftarget-config=' has no base.
   Without the check the first `->init_args' is a null call, which arrives as
   a SIGSEGV at address 0 and reads as a miscompile rather than as "you did
   not select a target".  */
static const struct target_cumargs_desc *
mt_cumargs (void)
{
  if (targetm_cumargs == NULL)
    internal_error ("no back end has been selected, so there is nothing to "
		    "initialise a %<CUMULATIVE_ARGS%> with; a target must be "
		    "chosen with %<-ftarget-config=%> before any function is "
		    "compiled");
  return targetm_cumargs;
}

void
mt_init_cumulative_args (cumulative_args_t ca, tree fntype, rtx libname,
			 tree fndecl, int n_named_args)
{
  mt_cumargs ()->init_args (ca, fntype, libname, fndecl, n_named_args);
}

void
mt_init_cumulative_incoming_args (cumulative_args_t ca, tree fntype,
				  rtx libname)
{
  mt_cumargs ()->init_incoming_args (ca, fntype, libname);
}

void
mt_init_cumulative_libcall_args (cumulative_args_t ca, machine_mode outmode,
				 rtx fun, int nargs)
{
  mt_cumargs ()->init_libcall_args (ca, outmode, fun, nargs);
}

int
mt_call_pops_args (cumulative_args_t ca)
{
  return mt_cumargs ()->call_pops_args (ca);
}

void
mt_override_abi_format (tree fndecl)
{
  mt_cumargs ()->override_abi_format (fndecl);
}

/* ------------------------------------------------------------------------
   THE FRAME AND ARGUMENT-REGISTER ANSWERS; see target-frame.h.

   `targetm_frame' is set beside `targetm_cumargs' by whoever selects a base,
   and is NOT derived from it here, so that a base selected for its argument
   accumulator but never given a frame table fails by name rather than
   answering with a stale pointer.  */
const struct target_frame_desc *targetm_frame;

static const struct target_frame_desc *
mt_frame (void)
{
  if (targetm_frame == NULL)
    internal_error ("no back end has been selected, so the frame layout of "
		    "the function being compiled is unknown; a target must be "
		    "chosen with %<-ftarget-config=%> before any function is "
		    "compiled");
  return targetm_frame;
}

int
mt_stack_boundary (void)
{
  return mt_frame ()->stack_boundary ();
}

int
mt_preferred_stack_boundary (void)
{
  return mt_frame ()->preferred_stack_boundary ();
}

unsigned int
mt_stack_slot_alignment (tree type, machine_mode mode, unsigned int align)
{
  return mt_frame ()->stack_slot_alignment (type, mode, align);
}

unsigned int
mt_minimum_alignment (tree exp, machine_mode mode, unsigned int align)
{
  return mt_frame ()->minimum_alignment (exp, mode, align);
}

int
mt_outgoing_reg_parm_stack_space (tree fntype)
{
  return mt_frame ()->outgoing_reg_parm_stack_space (fntype);
}

bool
mt_function_arg_regno_p (int regno)
{
  return mt_frame ()->function_arg_regno_p (regno);
}

/* `EPILOGUE_USES'.  Through `mt_frame ()' like the others, so a compilation
   with no target selected fails by name rather than reading a null table.
   That matters here in the way target-frame.h describes: a wrong `false' does
   not fault, it removes registers from the exit block's live set and lets DCE
   delete the instructions that wrote them.  */

bool
mt_epilogue_uses (int regno)
{
  return mt_frame ()->epilogue_uses (regno);
}

/* `ASM_DECLARE_FUNCTION_NAME' and its `#else' arm, collapsed into one call.
   The `#ifdef' now lives in the per-base thunk, so this is unconditional --
   see target-frame.h for why that is the point rather than a simplification.  */

void
mt_declare_function_name (FILE *file, const char *name, tree decl)
{
  mt_frame ()->declare_function_name (file, name, decl);
}

/* The cold-partition sibling; `final.cc:2229'.  */

void
mt_declare_cold_function_name (FILE *file, const char *name, tree decl)
{
  mt_frame ()->declare_cold_function_name (file, name, decl);
}

/* The stack-alignment closure; see target-frame.h.  These go through
   `mt_frame ()' like the six above, so a compilation with no target selected
   fails by name instead of reading a null table -- which matters more here
   than elsewhere, because `mt_supports_stack_alignment' guards an early
   `return' and a garbage `false' would look exactly like the correct answer
   for a back end that does not realign.  */

unsigned int
mt_incoming_stack_boundary (void)
{
  return mt_frame ()->incoming_stack_boundary ();
}

unsigned int
mt_max_stack_alignment (void)
{
  return mt_frame ()->max_stack_alignment ();
}

unsigned int
mt_max_supported_stack_alignment (void)
{
  return mt_frame ()->max_supported_stack_alignment ();
}

bool
mt_supports_stack_alignment (void)
{
  return mt_frame ()->supports_stack_alignment ();
}

/* ------------------------------------------------------------------------
   THE ELIMINATION TABLE; see target-frame.h.

   The two readers RANGE CHECK, and that is the reason they exist rather than
   shared code taking `targetm_frame->d_eliminables' and indexing it.  Every
   consumer bounds its loop by `mt_num_eliminable_regs ()', so an out-of-range
   index means a caller whose bound and whose index came from different
   authorities -- the exact fault this change is fixing, one level up.  Read
   unchecked it would return whatever `int' follows the table, and a register
   number is precisely the kind of value that stays plausible while being
   wrong; there is no downstream check that would object to it.

   The count is also asserted positive, so a table that never got supplied
   fails by name here instead of turning every consumer's loop into a no-op --
   `no eliminable registers at all' is a legal-looking answer that would make
   `ira_setup_eliminable_regset' silently do nothing.  */

static const struct target_frame_desc *
mt_elim_frame (void)
{
  const struct target_frame_desc *f = mt_frame ();

  if (f->n_eliminables <= 0 || f->d_eliminables == NULL
      || f->n_reload_eliminables <= 0 || f->d_reload_eliminables == NULL
      || f->initial_elimination_offset == NULL)
    internal_error ("back end %qs supplies no register-elimination table; its "
		    "objects and %<target-frame.h%> are from different builds",
		    f->name);
  return f;
}

int
mt_num_eliminable_regs (void)
{
  return mt_elim_frame ()->n_eliminables;
}

int
mt_num_reload_eliminable_regs (void)
{
  return mt_elim_frame ()->n_reload_eliminables;
}

int
mt_eliminable_from (int i)
{
  const struct target_frame_desc *f = mt_elim_frame ();

  if (i < 0 || i >= f->n_eliminables)
    internal_error ("elimination pair %d asked of back end %qs, which has %d "
		    "of them; the bound and the index come from different back "
		    "ends", i, f->name, f->n_eliminables);
  return f->d_eliminables[2 * i];
}

int
mt_eliminable_to (int i)
{
  const struct target_frame_desc *f = mt_elim_frame ();

  if (i < 0 || i >= f->n_eliminables)
    internal_error ("elimination pair %d asked of back end %qs, which has %d "
		    "of them; the bound and the index come from different back "
		    "ends", i, f->name, f->n_eliminables);
  return f->d_eliminables[2 * i + 1];
}

int
mt_reload_eliminable_from (int i)
{
  const struct target_frame_desc *f = mt_elim_frame ();

  if (i < 0 || i >= f->n_reload_eliminables)
    internal_error ("reload elimination pair %d asked of back end %qs, which "
		    "has %d of them; the bound and the index come from "
		    "different back ends", i, f->name, f->n_reload_eliminables);
  return f->d_reload_eliminables[2 * i];
}

int
mt_reload_eliminable_to (int i)
{
  const struct target_frame_desc *f = mt_elim_frame ();

  if (i < 0 || i >= f->n_reload_eliminables)
    internal_error ("reload elimination pair %d asked of back end %qs, which "
		    "has %d of them; the bound and the index come from "
		    "different back ends", i, f->name, f->n_reload_eliminables);
  return f->d_reload_eliminables[2 * i + 1];
}

poly_int64
mt_initial_elimination_offset (int from, int to)
{
  return mt_elim_frame ()->initial_elimination_offset (from, to);
}

/* `Pmode'.  Goes through `mt_frame ()' rather than caching, for the reason
   in target-frame.h: i386's is an option-dependent expression, so a value
   read once at startup would be frozen at whatever the options said then.  */
scalar_int_mode
mt_pmode (void)
{
  return mt_frame ()->pmode ();
}

/* THE OPTION-STATE FAMILY.  Uncached, through `mt_frame ()', and here the
   uncachedness is not merely consistent with `Pmode' -- it is REQUIRED, which
   is why the design was settled on correctness rather than on speed.

   `mavx' and `mavx512f' are `Save' options in `i386.opt', so
   `BIGGEST_ALIGNMENT' changes value WITHIN ONE COMPILATION when a function
   carries `__attribute__((target("avx512f")))'.  `stor-layout.cc' reads it
   during parsing, with no current function to key an invalidation on, so
   there is no point at which a cache could correctly be dropped.  A cached
   value would be frozen at whatever the command line said and would be wrong
   for exactly the translation units that use the attribute -- silently, and
   in a way no arm on a single-attribute-free test file could see.  The same
   argument applies to `UNITS_PER_WORD' and `POINTER_SIZE' through
   `TARGET_64BIT' / `TARGET_ILP32'.

   The measured cost of not caching is at the noise floor; see target-frame.h.
   No null check on the three pointers: `mt_move_max' above already fails by
   name on a table built against an older `target-frame.h', and repeating that
   test here would add three branches to the hottest accessors in the family
   to catch a condition one call already catches.  */
int
mt_units_per_word (void)
{
  return mt_frame ()->units_per_word ();
}

unsigned int
mt_pointer_size (void)
{
  return mt_frame ()->pointer_size ();
}

unsigned int
mt_biggest_alignment (void)
{
  return mt_frame ()->biggest_alignment ();
}

/* `FUNCTION_MODE'.  Uncached for the same reason as `Pmode' just above: eight
   back ends define it AS `Pmode', which is option-dependent on i386 and on
   arm, so a value read once at selection time would be frozen.  */
machine_mode
mt_function_mode (void)
{
  return mt_frame ()->function_mode ();
}

/* THE DWARF REGISTER-NUMBERING FAMILY.  Uncached, through `mt_frame ()', for
   the same reason as `Pmode' just above: i386's `DEBUGGER_REGNO' reads
   `TARGET_64BIT', which is option state and can move within one run of the
   compiler, and cygming's `DWARF_FRAME_REGISTERS' is `(TARGET_64BIT ? 33 : 17)'
   outright.  A value cached at selection time would be frozen at whatever the
   options said then -- the failure target-cdata.h's header comment records for
   `STACK_BOUNDARY'.

   No range check here, deliberately: the bound that matters is the SELECTED
   back end's `FIRST_PSEUDO_REGISTER', which only the base's own translation
   unit knows, so the test lives in `mt_base_debugger_regno' where that name
   means the right thing.  A second test here against the union width would
   pass on exactly the inputs the real one rejects.  */
unsigned int
mt_debugger_regno (unsigned int regno)
{
  return mt_frame ()->debugger_regno (regno);
}

unsigned int
mt_dwarf_frame_regnum (unsigned int regno)
{
  return mt_frame ()->dwarf_frame_regnum (regno);
}

unsigned int
mt_dwarf_frame_registers (void)
{
  return mt_frame ()->dwarf_frame_registers ();
}

/* Uncached through `mt_frame ()' for the same reason as the family above, and
   for one more that none of them has: epiphany's answer depends on
   `current_function_decl', so it changes between two functions of a single
   compilation, not merely between two option settings.  Caching anywhere --
   here, or in `target_cdata' where this used to live -- gives every epiphany
   interrupt handler the ordinary function's return column.  */
unsigned int
mt_dwarf_frame_return_column (void)
{
  return mt_frame ()->dwarf_frame_return_column ();
}

/* `DWARF2_UNWIND_INFO' for the selected base; see target-frame.h.

   THIS ONE CANNOT BE CALLED DIRECTLY BY ITS CONSUMER, AND THE ARCHIVE
   BOUNDARY IS THE REASON.  The consumer is `default_except_unwind_info' in
   `common/common-targhooks.cc', which is in `libcommon-target.a' -- linked
   into `xgcc', `cpp' and `lto-wrapper' as well as into `cc1'.  This file is
   in `libbackend.a', which the drivers do not link.  A call from there to
   here is an undefined symbol in three programs.

   So the answer travels through `mt_dwarf2_unwind_info_hook', a pointer
   DEFINED in libcommon-target and STORED by `multi_target_select' beside
   `targetm_frame' itself.  In a driver it stays null, which is correct rather
   than merely tolerable: measured, no driver source calls
   `except_unwind_info' at all, and the null path fails BY NAME rather than
   answering, so a future caller in a driver gets a diagnostic instead of
   UI_SJLJ for every target -- which is precisely the silent answer this whole
   change removes.  */
int
mt_dwarf2_unwind_info (void)
{
  return mt_frame ()->dwarf2_unwind_info ();
}

/* THE FOUR POINTER REGNUMS AND THE TWO DERIVED PREDICATES.  Uncached through
   `mt_frame ()' like the family above, and here the reason is not hypothetical:
   arm's `HARD_FRAME_POINTER_REGNUM' is
   `(TARGET_ARM ? ARM_HARD_FRAME_POINTER_REGNUM : THUMB_HARD_FRAME_POINTER_REGNUM)',
   so the answer moves with `-mthumb' inside a single run.  Caching at selection
   time would freeze the answer at whatever the options said then.

   NO RANGE CHECK AND NO SENTINEL, unlike `mt_debugger_regno': these take no
   argument.  Adding a plausibility test here -- "is the answer below
   `FIRST_PSEUDO_REGISTER'?" -- would be the mistake #126 records, because that
   name is the UNION width in this file (95) and the base's own count in the
   thunk, so the test would pass on precisely the wrong answers.  */
unsigned int
mt_stack_pointer_regnum (void)
{
  return mt_frame ()->stack_pointer_regnum ();
}

unsigned int
mt_frame_pointer_regnum (void)
{
  return mt_frame ()->frame_pointer_regnum ();
}

unsigned int
mt_hard_frame_pointer_regnum (void)
{
  return mt_frame ()->hard_frame_pointer_regnum ();
}

unsigned int
mt_arg_pointer_regnum (void)
{
  return mt_frame ()->arg_pointer_regnum ();
}

bool
mt_hard_frame_pointer_is_frame_pointer (void)
{
  return mt_frame ()->hard_frame_pointer_is_frame_pointer ();
}

bool
mt_hard_frame_pointer_is_arg_pointer (void)
{
  return mt_frame ()->hard_frame_pointer_is_arg_pointer ();
}

/* THE TWO CFA-AT-ENTRY OFFSETS.  Uncached through `mt_frame ()' like the
   families above, and here the reason is measured rather than hypothetical:
   i386's `INCOMING_FRAME_SP_OFFSET' reads `cfun->machine->func_type', so it
   is not even constant across two functions in one translation unit, let
   alone across a run.  A value cached at selection time would be read once
   with `cfun' null.  */
HOST_WIDE_INT
mt_incoming_frame_sp_offset (void)
{
  return mt_frame ()->incoming_frame_sp_offset ();
}

HOST_WIDE_INT
mt_default_incoming_frame_sp_offset (void)
{
  return mt_frame ()->default_incoming_frame_sp_offset ();
}

/* `ACCUMULATE_OUTGOING_ARGS'.  Uncached for the same reason as the pair above
   and one stronger: i386's body reads `crtl->stack_realign_needed', which is
   written during reload, so this is not constant even across two passes over
   one function.  */
bool
mt_accumulate_outgoing_args (void)
{
  return mt_frame ()->accumulate_outgoing_args ();
}

/* `STACK_DYNAMIC_OFFSET'.  Uncached for the same reasons again and one that
   is specific to it: the generic arm reads `crtl->outgoing_args_size', which
   is not known until after argument-block layout, and aarch64's arm reads
   `cfun->calls_alloca' and `flag_stack_clash_protection'.  There is no point
   in a run at which this has a single value.

   The `fndecl' is forwarded rather than being taken from
   `current_function_decl' here: function.cc's wrapper passes the latter
   today, but the macro's documented interface takes a decl and two back ends
   (pa, rs6000) actually read it.  */
poly_int64
mt_stack_dynamic_offset (tree fndecl)
{
  return mt_frame ()->stack_dynamic_offset (fndecl);
}

/* `PUSH_ARGS_REVERSED'.  Uncached, and here that is not merely conservative:
   the ladder's third arm is `targetm.calls.push_argument (0)', a target hook,
   and hooks are reachable only once a target is selected -- so there is no
   earlier point at which this HAS a value.  gimplify.cc evaluates it three
   times per call expression; that is the same shape as the ~40 sites
   `ACCUMULATE_OUTGOING_ARGS' already has.  */
bool
mt_push_args_reversed (void)
{
  return mt_frame ()->push_args_reversed ();
}

/* `INCOMING_REG_PARM_STACK_SPACE'.  Called once per function, from
   `assign_parms_initialize_all'.  The `fndecl' is forwarded rather than read
   from `current_function_decl' inside the thunk for the reason
   `mt_stack_dynamic_offset' records: the macro's interface takes a decl and
   several back ends read it.  */
int
mt_incoming_reg_parm_stack_space (tree fndecl)
{
  return mt_frame ()->incoming_reg_parm_stack_space (fndecl);
}

/* `REG_PARM_STACK_SPACE', existence and value.  Uncached, like every other
   member of this family: `has_' is a load and a compare, and the value one is
   a target hook call on i386 (`ix86_reg_parm_stack_space' reads
   `ix86_function_abi (fndecl)'), so it depends on the decl and cannot be
   cached per function anyway.

   `mt_reg_parm_stack_space' asserts the existence answer rather than trusting
   its callers.  Every shared value site sits under `if (mt_has_reg_parm_
   stack_space ())' today, and a site that stopped doing so would otherwise
   read the `#else' arm's 0 -- which is the primary's answer by another route,
   and indistinguishable from a real 0 exactly on the pair configured here.  */
bool
mt_has_reg_parm_stack_space (void)
{
  return mt_frame ()->has_reg_parm_stack_space ();
}

int
mt_reg_parm_stack_space (tree fndecl_or_type)
{
  gcc_assert (mt_frame ()->has_reg_parm_stack_space ());
  return mt_frame ()->reg_parm_stack_space (fndecl_or_type);
}

/* `PUSH_ROUNDING', existence and value.  The assertion is not decoration
   here: the `#else' arm of the per-base value thunk returns its argument
   unrounded, which is a PLAUSIBLE number -- it is what a target with
   `PUSH_ROUNDING(X) (X)' legitimately returns -- so a value site that escaped
   its existence test would produce believable wrong code rather than
   anything that fails.  */
bool
mt_has_push_rounding (void)
{
  return mt_frame ()->has_push_rounding ();
}

poly_int64
mt_push_rounding (poly_int64 bytes)
{
  gcc_assert (mt_frame ()->has_push_rounding ());
  return mt_frame ()->push_rounding (bytes);
}

/* `CASE_VECTOR_PC_RELATIVE' and `REGMODE_NATURAL_SIZE'.  Uncached, through
   `mt_frame ()', for the reason `Pmode' is: seven back ends spell the first
   as option state (`flag_pic', `riscv_cmodel', `rs6000_relative_jumptables',
   ...), and the second takes an argument, so there is no value to cache.  */
bool
mt_case_vector_pc_relative (void)
{
  return mt_frame ()->case_vector_pc_relative ();
}

poly_uint64
mt_regmode_natural_size (machine_mode mode)
{
  return mt_frame ()->regmode_natural_size (mode);
}

/* `CASE_VECTOR_MODE' and `INCOMING_RETURN_ADDR_RTX'.  Uncached, through
   `mt_frame ()', and here neither could be cached even in principle: the
   first is `flag_pic'-dependent on i386 and seven others, and the second
   BUILDS AN RTX, reading `stack_pointer_rtx' on i386 -- per-function state
   that does not exist until `init_emit_regs' has run for the current
   function.  A value sampled at selection time would be a dangling answer of
   exactly the kind `target-cdata.h:160' records for
   `PIC_OFFSET_TABLE_REGNUM'.  */
machine_mode
mt_case_vector_mode (void)
{
  return mt_frame ()->case_vector_mode ();
}

/* The existence half is a question shared code asks in its own right --
   `df-scan.cc:3558' used to spell it `#ifdef' -- so it is not merely a guard
   on the value below.  The `gcc_assert' is: the value thunk of a base that
   answers `false' here is `gcc_unreachable ()', so a value site reaching it
   would abort inside the back end's thunk with no clue which shared caller
   asked.  Failing at the boundary names the selection instead.  */
bool
mt_has_incoming_return_addr_rtx (void)
{
  return mt_frame ()->has_incoming_return_addr_rtx ();
}

rtx
mt_incoming_return_addr_rtx (void)
{
  gcc_assert (mt_frame ()->has_incoming_return_addr_rtx ());
  return mt_frame ()->incoming_return_addr_rtx ();
}

/* emit-rtl.cc's two `#ifdef INIT_EXPANDERS' sites, answered by the selected
   back end instead of by whichever base compiled emit-rtl.cc.

   The `has_init_expanders' / `init_expanders' pair is checked against itself
   here, not merely dereferenced.  A back end with nothing to run is a normal
   and common case -- 35 of the 48 are in it -- so a null pointer alone cannot
   be treated as an error; but a null pointer that the base did NOT claim, or
   a claim with no function behind it, is an object built against a different
   version of target-frame.h, and that has exactly one symptom otherwise:
   `cfun->machine' stays null and the back end faults on it much later.  This
   turns that into a diagnostic naming the base.  */
void
mt_init_expanders (void)
{
  const struct target_frame_desc *f = mt_frame ();

  if (f->has_init_expanders != (f->init_expanders != NULL))
    {
      if (f->has_init_expanders)
	internal_error ("back end %qs records that it defines "
			"%<INIT_EXPANDERS%> but supplies no function for it; "
			"its objects and %<target-frame.h%> are from "
			"different builds", f->name);
      else
	internal_error ("back end %qs records that it defines no "
			"%<INIT_EXPANDERS%> yet supplies a function for it; "
			"its objects and %<target-frame.h%> are from "
			"different builds", f->name);
    }

  if (f->init_expanders != NULL)
    f->init_expanders ();
}

/* ------------------------------------------------------------------------
   THE MOVE/CLEAR FAMILY; see target-frame.h.

   All seven forward unconditionally: there is no existence question here
   (measured -- every cpu back end defines `MOVE_MAX' and `defaults.h' floors
   the rest, evaluated per base), so there is no flag to check and a null
   pointer could only mean an object built against an older `target-frame.h'.
   That case is caught once, in `mt_move_max' below, rather than seven times.  */

/* `MAX_MOVE_MAX' MUST STILL BE A CONSTANT HERE, AND THIS IS NOT A FORMALITY.
   `defaults.h:1116' says `#define MAX_MOVE_MAX MOVE_MAX' for a back end that
   defines no `MAX_MOVE_MAX' of its own, and `MOVE_MAX' is now redirected to a
   call.  Today's primary, i386, defines `MAX_MOVE_MAX' as 64, so the floor
   does not fire -- but that is a fact about which back end happens to be the
   primary, which is precisely the kind of fact this project exists to stop
   depending on.  If it ever changes, this line fails the build by name, and
   `reload.h:179' and `caller-save.cc:55' -- which use `MAX_MOVE_MAX' as an
   ARRAY BOUND -- fail immediately after it.  Without this, the first symptom
   would be `mt_move_max' recursing into itself forever.  */
static_assert (MAX_MOVE_MAX > 0,
	       "MAX_MOVE_MAX is no longer a constant expression: the primary "
	       "back end has stopped defining it and defaults.h has derived "
	       "it from the redirected MOVE_MAX");

/* `MIN_UNITS_PER_WORD' MUST STILL BE A CONSTANT HERE, FOR THE SAME REASON AND
   BY THE SAME MECHANISM.  `defaults.h:1120' is
   `#define MIN_UNITS_PER_WORD UNITS_PER_WORD' for a back end that defines no
   `MIN_UNITS_PER_WORD' of its own, and `UNITS_PER_WORD' is now redirected to
   a call.  Today's primary, i386, defines it as a literal 4 (i386.h:770), so
   the floor does not fire -- but that is a fact about which back end happens
   to be the primary.  If it ever changes, this line fails the build by name,
   ahead of `caller-save.cc:55' and `reload.h:179' failing with a
   non-constant array bound and no mention of the macro that caused it.

   The two asserts are separate rather than one conjunction so that the
   message names the macro that actually stopped being constant.  */
static_assert (MIN_UNITS_PER_WORD > 0,
	       "MIN_UNITS_PER_WORD is no longer a constant expression: the "
	       "primary back end has stopped defining it and defaults.h has "
	       "derived it from the redirected UNITS_PER_WORD");

int
mt_move_max (void)
{
  const struct target_frame_desc *f = mt_frame ();

  /* The one check the whole family shares, and it is TWO-SIDED on purpose.
     Side one: the table must actually carry these fields.  A stale object
     shows up as a null pointer, and calling through it is a fault with no
     name attached; this makes it a diagnostic naming the base.
     Side two -- the half that catches a real bug rather than a stale build:
     `caller-save.cc' sizes `regno_save_mem' from the PRIMARY's
     `MAX_MOVE_MAX' and indexes it with `MOVE_MAX_WORDS', which this function
     now makes the SELECTED base's.  A base whose `MOVE_MAX' exceeds the
     primary's `MAX_MOVE_MAX' would run off the end of that array silently.
     Checking only the pointer would leave that overrun invisible; checking
     only the bound would not notice a stale table.  Neither alone is
     evidence, which is what makes this pair worth its cost.  */
  if (f->move_max == NULL)
    internal_error ("back end %qs supplies no %<MOVE_MAX%>; its objects and "
		    "%<target-frame.h%> are from different builds", f->name);

  int mm = f->move_max ();

  /* THE GUARD IS ON THE INDEX, NOT ON THE NUMERATOR, AND THAT CHANGED WITH
     THE `UNITS_PER_WORD' CONVERSION.  `caller-save.cc:55' and `reload.h:179'
     size `regno_save_mem[][MAX_MOVE_MAX / MIN_UNITS_PER_WORD + 1]' from
     constants, and index it with `MOVE_MAX_WORDS', i.e.
     `MOVE_MAX / UNITS_PER_WORD'.  Both halves of that quotient are now the
     SELECTED base's, so testing `mm > MAX_MOVE_MAX' alone is no longer
     sufficient: a base with a large `MOVE_MAX' and a small `UNITS_PER_WORD'
     produces an index the numerator test passes.  Comparing the quantities
     that are actually computed -- the index against the bound -- has no such
     gap, and it subsumes the old test rather than replacing it, since a
     larger numerator over an unchanged denominator still trips it.

     `mt_units_per_word' is called rather than spelling `UNITS_PER_WORD'
     because this file is shared and the macro is redirected here anyway; the
     call makes it obvious that the denominator is per-base and not a
     constant, which is the entire content of this check.  A zero or negative
     answer is refused separately: it would divide by zero here, and a back
     end reporting one is broken in a way worth naming.  */
  int upw = mt_units_per_word ();
  if (upw <= 0)
    internal_error ("back end %qs reports %<UNITS_PER_WORD%> of %d",
		    f->name, upw);

  /* THE BOUND IS NOW THE UNION ONE, NOT THIS TRANSLATION UNIT'S.  It used to
     be `MAX_MOVE_MAX / MIN_UNITS_PER_WORD + 1' read here, i.e. the PRIMARY's,
     which is the same defect the tables themselves had: shared code sized
     them at i386's 17 columns while aarch64's own objects computed 3 and read
     6664 bytes low in `struct target_reload'.  Both tables are now sized by
     MULTI_TARGET_UNION_REGNO_SAVE_MODE_COLS -- the measured maximum of the
     per-base quotient, which is the tight bound because base b never indexes
     past its own `MAX_MOVE_MAX_b / MIN_UNITS_PER_WORD_b' -- so the guard must
     compare against the same name or it is guarding a number nothing uses.  */
  const int bound = MULTI_TARGET_UNION_REGNO_SAVE_MODE_COLS;
  if (mm / upw >= bound)
    internal_error ("back end %qs moves %d bytes at a time with "
		    "%<UNITS_PER_WORD%> of %d, so shared code indexes the "
		    "caller-save tables at %d, but this compiler sized them "
		    "at %d; gen-reg-widths.sh did not see this back end",
		    f->name, mm, upw, mm / upw, bound);
  return mm;
}

int
mt_move_max_pieces (void)
{
  return mt_frame ()->move_max_pieces ();
}

int
mt_store_max_pieces (void)
{
  return mt_frame ()->store_max_pieces ();
}

int
mt_compare_max_pieces (void)
{
  return mt_frame ()->compare_max_pieces ();
}

int
mt_move_ratio (bool speed)
{
  return mt_frame ()->move_ratio (speed);
}

int
mt_clear_ratio (bool speed)
{
  return mt_frame ()->clear_ratio (speed);
}

int
mt_set_ratio (bool speed)
{
  return mt_frame ()->set_ratio (speed);
}

/* ------------------------------------------------------------------------
   `DATA_ALIGNMENT' / `DATA_ABI_ALIGNMENT'; see target-frame.h.

   The `(has_X, payload)' cross-check is the same one `mt_init_expanders'
   does and is here for the same reason, but the consequence of getting it
   wrong is different and worth naming: a missing INIT_EXPANDERS leaves
   `cfun->machine' null and faults, whereas a wrongly-absent DATA_ALIGNMENT
   just returns ALIGN and emits an under-aligned variable.  Nothing crashes
   and nothing is diagnosed; the object file is simply wrong.  So the state
   this checks is one whose failure mode is silent, which is exactly when a
   check earns its keep.  */

static void
/* HAVE_FN is passed as a `bool' the caller computed, not as the pointer
   itself: casting a pointer-to-function to `void *' is only
   conditionally-supported in C++ and this tree builds with
   `-Wconditionally-supported'.  The check is the same one either way.  */
mt_check_align_pair (const struct target_frame_desc *f, bool has,
		     bool have_fn, const char *macro)
{
  if (has == have_fn)
    return;
  if (has)
    internal_error ("back end %qs records that it defines %qs but supplies "
		    "no function for it; its objects and "
		    "%<target-frame.h%> are from different builds",
		    f->name, macro);
  else
    internal_error ("back end %qs records that it defines no %qs yet supplies "
		    "a function for it; its objects and "
		    "%<target-frame.h%> are from different builds",
		    f->name, macro);
}

unsigned int
mt_data_alignment (tree type, unsigned int align)
{
  const struct target_frame_desc *f = mt_frame ();

  mt_check_align_pair (f, f->has_data_alignment, f->data_alignment != NULL,
		       "DATA_ALIGNMENT");
  if (!f->has_data_alignment)
    return align;
  return f->data_alignment (type, align);
}

bool
mt_has_data_abi_alignment (void)
{
  const struct target_frame_desc *f = mt_frame ();

  mt_check_align_pair (f, f->has_data_abi_alignment,
		       f->data_abi_alignment != NULL,
		       "DATA_ABI_ALIGNMENT");
  return f->has_data_abi_alignment;
}

unsigned int
mt_data_abi_alignment (tree type, unsigned int align)
{
  const struct target_frame_desc *f = mt_frame ();

  if (!mt_has_data_abi_alignment ())
    return align;
  return f->data_abi_alignment (type, align);
}

/* ------------------------------------------------------------------------
   THE INSN-PATTERN EXISTENCE ANSWERS; see target-insn.h.

   NULL until a base is selected, like every other table here, and for the
   same reason: the plausible default is the primary's `insn-config.h', which
   is precisely the answer that was wrong.  */
const struct target_insn_desc *targetm_insn;

static const struct target_insn_desc *
mt_insn (void)
{
  if (targetm_insn == NULL)
    internal_error ("no back end has been selected, so which insn patterns "
		    "exist is unknown; a target must be chosen with "
		    "%<-ftarget-config=%> before any insn is simplified");
  return targetm_insn;
}

bool
mt_have_lo_sum (void)
{
  return mt_insn ()->have_lo_sum;
}

bool
mt_have_rotate (void)
{
  return mt_insn ()->have_rotate;
}

bool
mt_have_rotatert (void)
{
  return mt_insn ()->have_rotatert;
}

/* AUTO_INC_DEC -- whether the base in force has any auto-increment addressing
   at all.  25 of the 48 back ends say yes and i386 says no, so before this
   existed every one of them read i386's no.  */
bool
mt_auto_inc_dec (void)
{
  return mt_insn ()->auto_inc_dec;
}

/* LOAD_EXTEND_OP (MODE).  `int' in and `int' out because target-insn.h is
   reached before coretypes.h; `rtl.h''s use site casts back to
   `enum rtx_code'.  */
int
mt_load_extend_op (int mode)
{
  return mt_insn ()->load_extend_op (mode);
}

/* ------------------------------------------------------------------------
   THE CONSTRAINT VOCABULARY; see target-preds.h for the measurement.

   These are the definitions of the names `multi-target-preds.h' renames
   `tm-preds.h''s inline wrappers onto, so every constraint question shared
   code asks -- in recog.cc, lra-constraints.cc, ira.cc, ira-costs.cc,
   ira-lives.cc, ira-conflicts.cc, reload.cc, reload1.cc, postreload.cc,
   cse.cc, stmt.cc and varasm.cc -- is answered by the back end in force
   instead of by the primary.

   NULL until a base is selected, like every other table here.  The default
   that suggests itself is the primary's vocabulary, and that default is the
   entire bug: it does not fail, it answers.  */
const struct target_preds_desc *targetm_preds;

static const struct target_preds_desc *
mt_preds (void)
{
  if (targetm_preds == NULL)
    internal_error ("no back end has been selected, so no constraint letters "
		    "are defined; a target must be chosen with "
		    "%<-ftarget-config=%> before an insn is constrained");
  return targetm_preds;
}

int
mt_lookup_constraint (const char *p)
{
  return mt_preds ()->lookup (p);
}

bool
mt_constraint_satisfied_p (rtx x, int c)
{
  return mt_preds ()->satisfied_p (x, c);
}

int
mt_reg_class_for_constraint (int c)
{
  return mt_preds ()->reg_class_for (c);
}

int
mt_get_constraint_type (int c)
{
  return mt_preds ()->constraint_type (c);
}

bool
mt_insn_extra_register_constraint (int c)
{
  return mt_preds ()->extra_register (c);
}

bool
mt_insn_extra_memory_constraint (int c)
{
  return mt_preds ()->extra_memory (c);
}

bool
mt_insn_extra_special_memory_constraint (int c)
{
  return mt_preds ()->extra_special_memory (c);
}

bool
mt_insn_extra_relaxed_memory_constraint (int c)
{
  return mt_preds ()->extra_relaxed_memory (c);
}

bool
mt_insn_extra_address_constraint (int c)
{
  return mt_preds ()->extra_address (c);
}

void
mt_insn_extra_constraint_allows_reg_mem (int c, bool *allows_reg,
					 bool *allows_mem)
{
  mt_preds ()->allows_reg_mem (c, allows_reg, allows_mem);
}

size_t
mt_insn_constraint_len (char fc, const char *str)
{
  return mt_preds ()->constraint_len (fc, str);
}

bool
mt_insn_const_int_ok_for_constraint (HOST_WIDE_INT v, int c)
{
  return mt_preds ()->const_int_ok (v, c);
}

const HARD_REG_SET *
mt_get_register_filter (int c)
{
  return mt_preds ()->register_filter (c);
}

int
mt_get_register_filter_id (int c)
{
  return mt_preds ()->register_filter_id (c);
}

int
mt_get_dependent_filter_id (int c)
{
  return mt_preds ()->dependent_filter_id (c);
}

int
mt_get_dependent_filter_ref (int id)
{
  return mt_preds ()->dependent_filter_ref (id);
}

bool
mt_eval_dependent_filter (int id, unsigned int regno, machine_mode mode,
			  unsigned int ref_regno, machine_mode ref_mode)
{
  return mt_preds ()->eval_dependent (id, regno, mode, ref_regno, ref_mode);
}

/* THE ONE ENUMERATOR SHARED CODE SPELLS BY NAME (lra-constraints.cc:4055).
   A different number in every back end, so it is a read and not a constant.  */

int
mt_constraint_X (void)
{
  return mt_preds ()->constraint_X;
}

/* ------------------------------------------------------------------------
   THE INSN-ATTRIBUTE ENTRY POINTS; see target-attr.h for the measurement.

   These are the definitions of the names `multi-target-attr.h' renames
   `insn-attr.h''s declarations onto, so `recog.cc''s enabled-alternative
   masks and `final.cc''s instruction lengths are computed from the attribute
   tables of the back end in force instead of from the primary's.

   NULL until a base is selected, like every other table here.  The default
   that suggests itself is the primary's tables, and that default is the
   entire bug: it does not fail, it answers -- with an alternative mask for a
   different machine's insn code.  */
const struct target_attr_desc *targetm_attr;

static const struct target_attr_desc *
mt_attr (void)
{
  if (targetm_attr == NULL)
    internal_error ("no back end has been selected, so no insn attributes "
		    "are defined; a target must be chosen with "
		    "%<-ftarget-config=%> before an insn is recognised");
  return targetm_attr;
}

/* WHICH ATTRIBUTES THE SELECTED BASE HAS.  `recog.cc''s `have_bool_attr' and
   six sites in `final.cc' used to read these off the primary's `#if'.  */

bool
mt_have_attr_length (void)
{
  return mt_attr ()->have_attr_length;
}

bool
mt_have_attr_enabled (void)
{
  return mt_attr ()->have_attr_enabled;
}

bool
mt_have_attr_preferred_for_size (void)
{
  return mt_attr ()->have_attr_preferred_for_size;
}

bool
mt_have_attr_preferred_for_speed (void)
{
  return mt_attr ()->have_attr_preferred_for_speed;
}

int
mt_get_attr_enabled (rtx_insn *insn)
{
  return mt_attr ()->enabled (insn);
}

int
mt_get_attr_preferred_for_size (rtx_insn *insn)
{
  return mt_attr ()->preferred_for_size (insn);
}

int
mt_get_attr_preferred_for_speed (rtx_insn *insn)
{
  return mt_attr ()->preferred_for_speed (insn);
}

int
mt_insn_default_length (rtx_insn *insn)
{
  return mt_attr ()->default_length (insn);
}

int
mt_insn_min_length (rtx_insn *insn)
{
  return mt_attr ()->min_length (insn);
}

int
mt_insn_current_length (rtx_insn *insn)
{
  return mt_attr ()->current_length (insn);
}

/* ------------------------------------------------------------------------
   THE MODE-SWITCHING ENTITY LIST; see target-modeswitch.h for the
   measurement.

   `mode-switching.cc' used to wrap its pass gate and its whole body in a raw
   `#ifdef OPTIMIZE_MODE_SWITCHING' and to read `NUM_MODES_FOR_MODE_SWITCHING'
   into a file-scope array.  That object is shared, so both were the
   PRIMARY's: the gate said yes for forty-three back ends that define neither
   macro, and the three of them with no mode-switching hooks at all died on a
   null `targetm.mode_switching.*' slot -- frame `#0' at `0x0'.  */
const struct target_modeswitch_desc *targetm_modeswitch;

static const struct target_modeswitch_desc *
mt_modeswitch (void)
{
  if (targetm_modeswitch == NULL)
    internal_error ("no back end has been selected, so it is not known "
		    "whether this target switches modes; a target must be "
		    "chosen with %<-ftarget-config=%> before the "
		    "mode-switching pass runs");
  return targetm_modeswitch;
}

/* THE PASS GATE.  Zero entities is this back end's own answer -- it is what
   the absence of `OPTIMIZE_MODE_SWITCHING' from its `tm.h' already meant --
   and not a floor; see the long note in target-modeswitch.h.  */

bool
mt_mode_switching_p (void)
{
  return mt_modeswitch ()->n_entities > 0;
}

int
mt_mode_switch_n_entities (void)
{
  return mt_modeswitch ()->n_entities;
}

const int *
mt_mode_switch_num_modes (void)
{
  return mt_modeswitch ()->num_modes;
}

bool
mt_optimize_mode_switching (int entity)
{
  const struct target_modeswitch_desc *d = mt_modeswitch ();

  /* Not `if (d->optimize_p)': a base with entities and no predicate is a
     build bug, and returning false for it would silently disable the pass
     for a back end that asked for it -- the quiet direction.  The two
     fields come off one `#ifdef' in target-cumargs.cc, so this cannot
     happen without that file having been edited wrongly, which is exactly
     when a by-name failure is worth having.  */
  if (d->n_entities == 0)
    return false;
  if (d->optimize_p == NULL)
    internal_error ("back end %qs lists %d mode-switching entities but "
		    "supplies no %<OPTIMIZE_MODE_SWITCHING%> predicate",
		    d->name, d->n_entities);
  return d->optimize_p (entity);
}

/* ------------------------------------------------------------------------
   THE SCHEDULER-ATTRIBUTE INITIALISER; see target-sched.h for the
   measurement.  Exactly one of the twelve `init_sched_attrs' in an
   eleven-base `cc1' ever ran -- the bare, primary one -- so every other
   base's `internal_dfa_insn_code' stayed NULL and a back end asking its own
   automaton called through address `0x0'.  */
const struct target_sched_desc *targetm_sched;

void
mt_init_base_sched_attrs (void)
{
  if (targetm_sched == NULL)
    internal_error ("no back end has been selected, so its scheduling "
		    "attributes cannot be initialised; a target must be "
		    "chosen with %<-ftarget-config=%> before RTL is "
		    "generated");
  if (targetm_sched->init_attrs != NULL)
    targetm_sched->init_attrs ();
}

/* ------------------------------------------------------------------------
   THE `asm_fprintf' FORMAT EXTENSIONS; see target-asmfprintf.h for the
   measurement.  `final.o' is shared, so its `#ifdef ASM_FPRINTF_EXTENSIONS'
   and the macro body inside it were the PRIMARY's for every base -- and the
   two definers, i386 and arm, give the same letter `%r' two different
   meanings.  arm reached `gcc_unreachable ()' in `asm_fprintf' on its `%@'
   the first time it got as far as `final'.  */
const struct target_asmfprintf_desc *targetm_asmfprintf;

bool
mt_asm_fprintf_extension (FILE *file, va_list *args, int c)
{
  if (targetm_asmfprintf == NULL)
    internal_error ("no back end has been selected, so it is not known which "
		    "%<asm_fprintf%> format extensions exist; a target must "
		    "be chosen with %<-ftarget-config=%> before assembly is "
		    "written");
  /* A null `extension' is this base's own answer -- forty-six back ends
     define no `ASM_FPRINTF_EXTENSIONS' at all -- and false sends the caller
     to `gcc_unreachable ()', which is exactly what upstream does for such a
     target.  */
  if (targetm_asmfprintf->extension == NULL)
    return false;
  return targetm_asmfprintf->extension (file, args, c);
}

/* Whether the selected back end has assembler dialects, and which.  Two of
   forty-eight define `ASSEMBLER_DIALECT'; `final.o' is shared, so its
   `#ifdef' was true for all forty-eight, and `%|' in arm's templates printed
   a literal `|' instead of arm's (empty) REGISTER_PREFIX.  */

bool
mt_have_assembler_dialect (void)
{
  if (targetm_asmfprintf == NULL)
    internal_error ("no back end has been selected, so it is not known "
		    "whether this target has assembler dialects; a target "
		    "must be chosen with %<-ftarget-config=%> before assembly "
		    "is written");
  return targetm_asmfprintf->has_assembler_dialect;
}

int
mt_assembler_dialect (void)
{
  /* Not `if (assembler_dialect)': a base claiming dialects with no value is a
     build bug, and answering 0 for it would silently select the first
     alternative of every template -- the quiet direction.  The two fields
     come off one `#ifdef' in target-cumargs.cc, so this cannot happen without
     that file having been edited wrongly.  */
  if (!mt_have_assembler_dialect ())
    internal_error ("back end %qs has no assembler dialects, so none can be "
		    "in force", targetm_asmfprintf->name);
  if (targetm_asmfprintf->assembler_dialect == NULL)
    internal_error ("back end %qs claims assembler dialects but supplies no "
		    "%<ASSEMBLER_DIALECT%> value", targetm_asmfprintf->name);
  return targetm_asmfprintf->assembler_dialect ();
}

/* ------------------------------------------------------------------------
   THE DFA PIPELINE-HAZARD ENTRY POINTS; see target-automata.h for the
   measurement.

   These are the definitions of the names `multi-target-attr.h' renames
   `insn-attr.h''s declarations onto, so `haifa-sched.o', `sched-rgn.o',
   `modulo-sched.o' and `sel-sched*.o' drive the automaton of the back end in
   force instead of the primary's.

   THIS ONE IS A MEMORY-SAFETY FIX AND NOT ONLY A MODELLING ONE.  The DFA
   state is a variable-length object, and `state_size' -- the length -- was
   one of the leaking entry points: ia64 sized `prev_cycle_state' at 4 bytes
   from its own automaton, `sched_init' then overwrote the shared
   `dfa_state_size' with the bare (i386) 116, and `ia64_variable_issue'
   memcpyed 116 bytes into the 4-byte buffer.  Six ASAN runs of six.  */
const struct target_automata_desc *targetm_automata;

/* NULL until a base is selected, like every other table here, and a base
   with no automaton is refused BY NAME rather than answered.

   That refusal is the honest state of a residual this change does not close:
   shared scheduling code is wrapped in `#ifdef INSN_SCHEDULING', which is the
   PRIMARY's macro, so a base with no `define_insn_reservation' beside a
   primary that has one still reaches here.  Upstream that combination cannot
   arise.  Failing by name is the loud direction; see target-automata.h.  */
static const struct target_automata_desc *
mt_automata (void)
{
  if (targetm_automata == NULL)
    internal_error ("no back end has been selected, so it has no pipeline "
		    "automaton; a target must be chosen with "
		    "%<-ftarget-config=%> before instructions are scheduled");
  if (!targetm_automata->has_dfa)
    internal_error ("back end %qs has no pipeline automaton, but shared "
		    "scheduling code compiled for a primary that has one is "
		    "asking it for pipeline hazards",
		    targetm_automata->name);
  return targetm_automata;
}

int
mt_state_size (void)
{
  return mt_automata ()->size ();
}

int
mt_max_insn_queue_index (void)
{
  return mt_automata ()->max_queue_index ();
}

void
mt_state_reset (void *s)
{
  mt_automata ()->reset (s);
}

int
mt_state_transition (void *s, rtx insn)
{
  return mt_automata ()->transition (s, insn);
}

int
mt_state_dead_lock_p (void *s)
{
  return mt_automata ()->dead_lock_p (s);
}

int
mt_min_insn_conflict_delay (void *s, rtx_insn *a, rtx_insn *b)
{
  return mt_automata ()->min_conflict_delay (s, a, b);
}

void
mt_print_reservation (FILE *f, rtx_insn *insn)
{
  mt_automata ()->print_res (f, insn);
}

void
mt_dfa_start (void)
{
  mt_automata ()->start ();
}

void
mt_dfa_finish (void)
{
  mt_automata ()->finish ();
}

void
mt_dfa_clear_single_insn_cache (rtx_insn *insn)
{
  mt_automata ()->clear_single_cache (insn);
}

int
mt_bypass_p (rtx_insn *insn)
{
  return mt_automata ()->bypass (insn);
}

int
mt_insn_latency (rtx_insn *a, rtx_insn *b)
{
  return mt_automata ()->latency (a, b);
}

int
mt_maximal_insn_latency (rtx_insn *insn)
{
  return mt_automata ()->max_latency (insn);
}

int
mt_insn_default_latency (rtx_insn *insn)
{
  return mt_automata ()->default_latency (insn);
}
