/* Selection between the back ends' register-stack tables.
   Copyright (C) 2026 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 3, or (at your option) any later
version.

GCC is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#include "config.h"
#include "system.h"
#include "coretypes.h"
/* tm.h, for the same reason every other *-select.cc includes it: rtl.h is
   unusable without it (FIRST_PSEUDO_REGISTER, BITS_PER_WORD, enum reg_class).
   Nothing target-specific is READ here -- this file is a by-name lookup and
   one indirection -- but rtl.h is needed for the declaration of
   `stack_regs_mentioned' to be in scope where it is defined, so that a
   signature drift is a compile error rather than a second overload.  */
#include "rtl.h"
#include "target-regstack.h"

/* Declares every configured back end's table and defines
   TARGETM_REGSTACK_TABLES listing them.  Generated by
   gen-multi-target-md.awk.  */
#include "multi-target-regstack.h"

#define TARGETM_REGSTACK_ENTRY(NAME, SYM) { NAME, &SYM },
const struct target_regstack_entry targetm_regstack_registry[] = {
  TARGETM_REGSTACK_TABLES
  { NULL, NULL }
};
#undef TARGETM_REGSTACK_ENTRY

/* NULL, not the primary's table.  See target-regstack.h.  */
const struct target_regstack_desc *targetm_regstack;

const struct target_regstack_desc *
target_regstack_for (const char *base)
{
  for (const struct target_regstack_entry *e = targetm_regstack_registry;
       e->name != NULL; e++)
    if (strcmp (e->name, base) == 0)
      return e->regstack;
  return NULL;
}

/* THE ONE EXTERNAL DEFINITION OF THIS NAME IN THE COMPILER.

   rtl.h:4651 declares it unconditionally and cfgcleanup.cc:1246 calls it on
   every target, having replaced its own `#ifdef STACK_REGS' with a run-time
   question -- and a run-time test cannot elide a link-time reference, so the
   symbol has to exist wherever its caller does.  That sentence used to be a
   comment in reg-stack.cc explaining an `#ifndef STACK_REGS' arm; it is now
   the reason this wrapper is here rather than in the per-base file, which
   would define the name once per back end.

   False when no target has been selected and false for a base with no
   register stack: both are "this insn does not mention a stack register",
   which is what the old `#ifndef' arm returned, and neither is a fallback to
   the primary's answer -- there is no primary's answer to fall back to, the
   selected base either has the pass or it does not.  */

bool
stack_regs_mentioned (const_rtx insn)
{
  if (targetm_regstack == NULL || targetm_regstack->stack_regs_mentioned == NULL)
    return false;
  return targetm_regstack->stack_regs_mentioned (insn);
}
