/* Which back end's assembler directives are in force.
   Copyright (C) 2026 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 3, or (at your option) any later
version.

GCC is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#include "config.h"
#include "system.h"
#include "coretypes.h"
#include "target.h"
/* For internal_error in mt_asm_output_align below.  */
#include "diagnostic-core.h"
#include "target-asm-ops.h"

/* Declares every configured back end's table and defines
   TARGETM_ASM_OPS_TABLES listing them.  Generated by gen-multi-target-md.awk
   from multi-target.manifest.  */
#include "multi-target-asm-ops.h"

/* Naming every table here is not merely descriptive.  It follows
   common/common-target-select.cc: an object nothing refers to is not pulled
   out of an archive, so without a reference the only table reaching the
   compiler would be whichever one something else happened to mention.  */
#define TARGETM_ASM_OPS_ENTRY(NAME, SYM) { NAME, &SYM },
const struct target_asm_ops_entry targetm_asm_ops_registry[] = {
  TARGETM_ASM_OPS_TABLES
  { NULL, NULL }
};
#undef TARGETM_ASM_OPS_ENTRY

/* The table in force.  Constant-initialised with the address of the
   configured target's table, which is a constant expression: no dynamic
   initialisation, so this is valid before anything runs.  Holding a struct
   here and copying into it would be dynamically initialised, and anything
   running before the copy would read null directives -- a wrong section
   rather than a link failure.  */
const struct target_asm_ops *targetm_asm_ops = &TARGETM_ASM_OPS_SYMBOL;

const struct target_asm_ops *
target_asm_ops_for (const char *base)
{
  for (const struct target_asm_ops_entry *e = targetm_asm_ops_registry;
       e->name != NULL; e++)
    if (strcmp (e->name, base) == 0)
      return e->ops;
  return NULL;
}

/* Copy the selected table into targetm.asm_out.
   `targetm' is not const -- each back end defines it as
   `struct gcc_target targetm = TARGET_INITIALIZER;' -- so the POD hooks can
   simply be overwritten here, and every consumer keeps reading targetm.

   ORDERING: this must run before init_varasm_once (toplev.cc), which caches
   the section directives into section objects.  Note also that
   read_target_caps runs *later* than init_varasm_once, so nothing selected
   here may depend on a probed capability: the table is chosen by target
   identity alone, which is why this is safe.  Anyone wanting a section
   directive to depend on something probed has to move the capability read
   earlier first -- the failure would otherwise be a silently wrong section
   directive, not a crash.  */

void
init_targetm_asm_ops (void)
{
  const struct target_asm_ops *ops = targetm_asm_ops;

  if (ops == NULL)
    return;

  targetm.asm_out.global_op = ops->global_op;
  targetm.asm_out.text_section_asm_op = ops->text_section_asm_op;
  targetm.asm_out.data_section_asm_op = ops->data_section_asm_op;
  targetm.asm_out.sdata_section_asm_op = ops->sdata_section_asm_op;
  targetm.asm_out.readonly_data_section_asm_op
    = ops->readonly_data_section_asm_op;
  targetm.asm_out.bss_section_asm_op = ops->bss_section_asm_op;
  targetm.asm_out.sbss_section_asm_op = ops->sbss_section_asm_op;
  targetm.asm_out.ctors_section_asm_op = ops->ctors_section_asm_op;
  targetm.asm_out.dtors_section_asm_op = ops->dtors_section_asm_op;
  targetm.asm_out.init_section_asm_op = ops->init_section_asm_op;
}

/* ASM_OUTPUT_ALIGN for the base in force.

   NOT copied into `targetm.asm_out' above, because the macro has no `targetm'
   counterpart to be copied into; `multi-target-macros.h' redirects the macro
   straight here instead.

   THE NULL CHECK IS NOT DEFENSIVE PADDING.  `targetm_asm_ops' is initialised
   to `&TARGETM_ASM_OPS_SYMBOL' -- the PRIMARY's table -- so that a
   `multi_target_select' which never ran leaves this function quietly emitting
   i386's directive, which is the exact defect being removed and would be
   indistinguishable from success.  A null `output_align' is the one shape
   that can be detected from here, and it fails by name.  */

void
mt_asm_output_align (FILE *stream, int log)
{
  if (targetm_asm_ops == NULL || targetm_asm_ops->output_align == NULL)
    internal_error ("no back end has been selected, so the %<.align%> "
		    "directive spelling is unknown; a target must be chosen "
		    "with %<-ftarget-config=%> before assembly is emitted");
  targetm_asm_ops->output_align (stream, log);
}
