/* Which back end writes a CUMULATIVE_ARGS, and the shared-code entry points.
   Copyright (C) 2026 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 3, or (at your option) any later
version.

GCC is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#include "config.h"
#include "system.h"
#include "coretypes.h"
#include "tm.h"
#include "rtl.h"
#include "tree.h"
#include "target.h"
#include "diagnostic-core.h"
#include "target-cumargs.h"

/* Declares every configured back end's table and defines TARGETM_CUMARGS_TABLES
   listing them.  Generated by gen-multi-target-md.awk.  */
#include "multi-target-cumargs.h"

#define TARGETM_CUMARGS_ENTRY(NAME, SYM) { NAME, &SYM },
const struct target_cumargs_entry targetm_cumargs_registry[] = {
  TARGETM_CUMARGS_TABLES
  { NULL, NULL }
};
#undef TARGETM_CUMARGS_ENTRY

/* NULL, not the primary's table.  See target-regs.h for the argument at
   length: a default here compiles aarch64 arguments with i386's
   argument-passing state, in bounds and with no diagnostic.  */
const struct target_cumargs_desc *targetm_cumargs;

const struct target_cumargs_desc *
target_cumargs_for (const char *base)
{
  for (const struct target_cumargs_entry *e = targetm_cumargs_registry;
       e->name != NULL; e++)
    if (strcmp (e->name, base) == 0)
      return e->cumargs;
  return NULL;
}

/* The shared-code entry points.  Each is one indirection with a by-name check
   in front of it.

   THE CHECK IS NOT DEFENSIVE PROGRAMMING.  These are on the path every
   function compilation takes, and the state they guard against -- no target
   selected -- is reachable: `cc1' without `-ftarget-config=' has no base.
   Without the check the first `->init_args' is a null call, which arrives as
   a SIGSEGV at address 0 and reads as a miscompile rather than as "you did
   not select a target".  */
static const struct target_cumargs_desc *
mt_cumargs (void)
{
  if (targetm_cumargs == NULL)
    internal_error ("no back end has been selected, so there is nothing to "
		    "initialise a %<CUMULATIVE_ARGS%> with; a target must be "
		    "chosen with %<-ftarget-config=%> before any function is "
		    "compiled");
  return targetm_cumargs;
}

void
mt_init_cumulative_args (cumulative_args_t ca, tree fntype, rtx libname,
			 tree fndecl, int n_named_args)
{
  mt_cumargs ()->init_args (ca, fntype, libname, fndecl, n_named_args);
}

void
mt_init_cumulative_incoming_args (cumulative_args_t ca, tree fntype,
				  rtx libname)
{
  mt_cumargs ()->init_incoming_args (ca, fntype, libname);
}

void
mt_init_cumulative_libcall_args (cumulative_args_t ca, machine_mode outmode,
				 rtx fun, int nargs)
{
  mt_cumargs ()->init_libcall_args (ca, outmode, fun, nargs);
}

int
mt_call_pops_args (cumulative_args_t ca)
{
  return mt_cumargs ()->call_pops_args (ca);
}

void
mt_override_abi_format (tree fndecl)
{
  mt_cumargs ()->override_abi_format (fndecl);
}

/* ------------------------------------------------------------------------
   THE FRAME AND ARGUMENT-REGISTER ANSWERS; see target-frame.h.

   `targetm_frame' is set beside `targetm_cumargs' by whoever selects a base,
   and is NOT derived from it here, so that a base selected for its argument
   accumulator but never given a frame table fails by name rather than
   answering with a stale pointer.  */
const struct target_frame_desc *targetm_frame;

static const struct target_frame_desc *
mt_frame (void)
{
  if (targetm_frame == NULL)
    internal_error ("no back end has been selected, so the frame layout of "
		    "the function being compiled is unknown; a target must be "
		    "chosen with %<-ftarget-config=%> before any function is "
		    "compiled");
  return targetm_frame;
}

int
mt_stack_boundary (void)
{
  return mt_frame ()->stack_boundary ();
}

int
mt_preferred_stack_boundary (void)
{
  return mt_frame ()->preferred_stack_boundary ();
}

unsigned int
mt_stack_slot_alignment (tree type, machine_mode mode, unsigned int align)
{
  return mt_frame ()->stack_slot_alignment (type, mode, align);
}

unsigned int
mt_minimum_alignment (tree exp, machine_mode mode, unsigned int align)
{
  return mt_frame ()->minimum_alignment (exp, mode, align);
}

int
mt_outgoing_reg_parm_stack_space (tree fntype)
{
  return mt_frame ()->outgoing_reg_parm_stack_space (fntype);
}

bool
mt_function_arg_regno_p (int regno)
{
  return mt_frame ()->function_arg_regno_p (regno);
}

/* The stack-alignment closure; see target-frame.h.  These go through
   `mt_frame ()' like the six above, so a compilation with no target selected
   fails by name instead of reading a null table -- which matters more here
   than elsewhere, because `mt_supports_stack_alignment' guards an early
   `return' and a garbage `false' would look exactly like the correct answer
   for a back end that does not realign.  */

unsigned int
mt_incoming_stack_boundary (void)
{
  return mt_frame ()->incoming_stack_boundary ();
}

unsigned int
mt_max_stack_alignment (void)
{
  return mt_frame ()->max_stack_alignment ();
}

unsigned int
mt_max_supported_stack_alignment (void)
{
  return mt_frame ()->max_supported_stack_alignment ();
}

bool
mt_supports_stack_alignment (void)
{
  return mt_frame ()->supports_stack_alignment ();
}

/* emit-rtl.cc's two `#ifdef INIT_EXPANDERS' sites, answered by the selected
   back end instead of by whichever base compiled emit-rtl.cc.

   The `has_init_expanders' / `init_expanders' pair is checked against itself
   here, not merely dereferenced.  A back end with nothing to run is a normal
   and common case -- 35 of the 48 are in it -- so a null pointer alone cannot
   be treated as an error; but a null pointer that the base did NOT claim, or
   a claim with no function behind it, is an object built against a different
   version of target-frame.h, and that has exactly one symptom otherwise:
   `cfun->machine' stays null and the back end faults on it much later.  This
   turns that into a diagnostic naming the base.  */
void
mt_init_expanders (void)
{
  const struct target_frame_desc *f = mt_frame ();

  if (f->has_init_expanders != (f->init_expanders != NULL))
    {
      if (f->has_init_expanders)
	internal_error ("back end %qs records that it defines "
			"%<INIT_EXPANDERS%> but supplies no function for it; "
			"its objects and %<target-frame.h%> are from "
			"different builds", f->name);
      else
	internal_error ("back end %qs records that it defines no "
			"%<INIT_EXPANDERS%> yet supplies a function for it; "
			"its objects and %<target-frame.h%> are from "
			"different builds", f->name);
    }

  if (f->init_expanders != NULL)
    f->init_expanders ();
}

/* ------------------------------------------------------------------------
   THE MOVE/CLEAR FAMILY; see target-frame.h.

   All seven forward unconditionally: there is no existence question here
   (measured -- every cpu back end defines `MOVE_MAX' and `defaults.h' floors
   the rest, evaluated per base), so there is no flag to check and a null
   pointer could only mean an object built against an older `target-frame.h'.
   That case is caught once, in `mt_move_max' below, rather than seven times.  */

/* `MAX_MOVE_MAX' MUST STILL BE A CONSTANT HERE, AND THIS IS NOT A FORMALITY.
   `defaults.h:1116' says `#define MAX_MOVE_MAX MOVE_MAX' for a back end that
   defines no `MAX_MOVE_MAX' of its own, and `MOVE_MAX' is now redirected to a
   call.  Today's primary, i386, defines `MAX_MOVE_MAX' as 64, so the floor
   does not fire -- but that is a fact about which back end happens to be the
   primary, which is precisely the kind of fact this project exists to stop
   depending on.  If it ever changes, this line fails the build by name, and
   `reload.h:179' and `caller-save.cc:55' -- which use `MAX_MOVE_MAX' as an
   ARRAY BOUND -- fail immediately after it.  Without this, the first symptom
   would be `mt_move_max' recursing into itself forever.  */
static_assert (MAX_MOVE_MAX > 0,
	       "MAX_MOVE_MAX is no longer a constant expression: the primary "
	       "back end has stopped defining it and defaults.h has derived "
	       "it from the redirected MOVE_MAX");

int
mt_move_max (void)
{
  const struct target_frame_desc *f = mt_frame ();

  /* The one check the whole family shares, and it is TWO-SIDED on purpose.
     Side one: the table must actually carry these fields.  A stale object
     shows up as a null pointer, and calling through it is a fault with no
     name attached; this makes it a diagnostic naming the base.
     Side two -- the half that catches a real bug rather than a stale build:
     `caller-save.cc' sizes `regno_save_mem' from the PRIMARY's
     `MAX_MOVE_MAX' and indexes it with `MOVE_MAX_WORDS', which this function
     now makes the SELECTED base's.  A base whose `MOVE_MAX' exceeds the
     primary's `MAX_MOVE_MAX' would run off the end of that array silently.
     Checking only the pointer would leave that overrun invisible; checking
     only the bound would not notice a stale table.  Neither alone is
     evidence, which is what makes this pair worth its cost.  */
  if (f->move_max == NULL)
    internal_error ("back end %qs supplies no %<MOVE_MAX%>; its objects and "
		    "%<target-frame.h%> are from different builds", f->name);

  int mm = f->move_max ();
  if (mm > MAX_MOVE_MAX)
    internal_error ("back end %qs moves %d bytes at a time but this compiler "
		    "was built with %<MAX_MOVE_MAX%> of %d; the caller-save "
		    "tables are sized by the latter and indexed by the "
		    "former", f->name, mm, (int) MAX_MOVE_MAX);
  return mm;
}

int
mt_move_max_pieces (void)
{
  return mt_frame ()->move_max_pieces ();
}

int
mt_store_max_pieces (void)
{
  return mt_frame ()->store_max_pieces ();
}

int
mt_compare_max_pieces (void)
{
  return mt_frame ()->compare_max_pieces ();
}

int
mt_move_ratio (bool speed)
{
  return mt_frame ()->move_ratio (speed);
}

int
mt_clear_ratio (bool speed)
{
  return mt_frame ()->clear_ratio (speed);
}

int
mt_set_ratio (bool speed)
{
  return mt_frame ()->set_ratio (speed);
}

/* ------------------------------------------------------------------------
   `DATA_ALIGNMENT' / `DATA_ABI_ALIGNMENT'; see target-frame.h.

   The `(has_X, payload)' cross-check is the same one `mt_init_expanders'
   does and is here for the same reason, but the consequence of getting it
   wrong is different and worth naming: a missing INIT_EXPANDERS leaves
   `cfun->machine' null and faults, whereas a wrongly-absent DATA_ALIGNMENT
   just returns ALIGN and emits an under-aligned variable.  Nothing crashes
   and nothing is diagnosed; the object file is simply wrong.  So the state
   this checks is one whose failure mode is silent, which is exactly when a
   check earns its keep.  */

static void
/* HAVE_FN is passed as a `bool' the caller computed, not as the pointer
   itself: casting a pointer-to-function to `void *' is only
   conditionally-supported in C++ and this tree builds with
   `-Wconditionally-supported'.  The check is the same one either way.  */
mt_check_align_pair (const struct target_frame_desc *f, bool has,
		     bool have_fn, const char *macro)
{
  if (has == have_fn)
    return;
  if (has)
    internal_error ("back end %qs records that it defines %qs but supplies "
		    "no function for it; its objects and "
		    "%<target-frame.h%> are from different builds",
		    f->name, macro);
  else
    internal_error ("back end %qs records that it defines no %qs yet supplies "
		    "a function for it; its objects and "
		    "%<target-frame.h%> are from different builds",
		    f->name, macro);
}

unsigned int
mt_data_alignment (tree type, unsigned int align)
{
  const struct target_frame_desc *f = mt_frame ();

  mt_check_align_pair (f, f->has_data_alignment, f->data_alignment != NULL,
		       "DATA_ALIGNMENT");
  if (!f->has_data_alignment)
    return align;
  return f->data_alignment (type, align);
}

bool
mt_has_data_abi_alignment (void)
{
  const struct target_frame_desc *f = mt_frame ();

  mt_check_align_pair (f, f->has_data_abi_alignment,
		       f->data_abi_alignment != NULL,
		       "DATA_ABI_ALIGNMENT");
  return f->has_data_abi_alignment;
}

unsigned int
mt_data_abi_alignment (tree type, unsigned int align)
{
  const struct target_frame_desc *f = mt_frame ();

  if (!mt_has_data_abi_alignment ())
    return align;
  return f->data_abi_alignment (type, align);
}

/* ------------------------------------------------------------------------
   THE INSN-PATTERN EXISTENCE ANSWERS; see target-insn.h.

   NULL until a base is selected, like every other table here, and for the
   same reason: the plausible default is the primary's `insn-config.h', which
   is precisely the answer that was wrong.  */
const struct target_insn_desc *targetm_insn;

static const struct target_insn_desc *
mt_insn (void)
{
  if (targetm_insn == NULL)
    internal_error ("no back end has been selected, so which insn patterns "
		    "exist is unknown; a target must be chosen with "
		    "%<-ftarget-config=%> before any insn is simplified");
  return targetm_insn;
}

bool
mt_have_lo_sum (void)
{
  return mt_insn ()->have_lo_sum;
}

bool
mt_have_rotate (void)
{
  return mt_insn ()->have_rotate;
}

bool
mt_have_rotatert (void)
{
  return mt_insn ()->have_rotatert;
}
