dnl Copyright (C) 2026 Free Software Foundation, Inc.
dnl This file is free software, distributed under the terms of the GNU
dnl General Public License.  As a special exception to the GNU General
dnl Public License, this file may be distributed as part of a program
dnl that contains a configuration script generated by Autoconf, under
dnl the same distribution terms as the rest of that program.

dnl Support for linking an installed libbacktrace rather than the copy that
dnl lives in the GCC tree.
AC_DEFUN([GCC_WITH_SYSTEM_LIBBACKTRACE], [
  AC_ARG_WITH([system-libbacktrace],
    AS_HELP_STRING([--with-system-libbacktrace],
      [link an installed libbacktrace instead of the copy in the GCC tree]),
    [with_system_libbacktrace=$withval],
    [with_system_libbacktrace=no])

  dnl No e.g. paths supported at this time, just yes or no.
  case "$with_system_libbacktrace" in
    yes|no) ;;
    *) AC_MSG_ERROR([--with-system-libbacktrace does not take an argument]) ;;
  esac
])

dnl Insist the installed library is really there, so that its absence is
dnl reported here rather than as an undefined reference at the end of a build.
dnl
dnl Separate from the option itself, because a component may not know whether
dnl it needs libbacktrace at the point the option is parsed: libstdc++
dnl resolves --enable-libstdcxx-backtrace=auto much later, and should
dnl not demand a library it has decided *not* to use.
AC_DEFUN([GCC_CHECK_SYSTEM_LIBBACKTRACE], [
  AC_REQUIRE([GCC_WITH_SYSTEM_LIBBACKTRACE])
  if test "x$with_system_libbacktrace" = xyes; then
    AC_CHECK_HEADER([backtrace.h], [],
      [AC_MSG_ERROR([--with-system-libbacktrace given, but backtrace.h not found])])
  fi
])
